### ISSUE TITLE
Additional design support for more complex forms

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly-design#1010]
Our form designs seem to start to break down a bit with complexity beyond our basic examples. I think it will be worth exploring the addition of a bit more structure that could better support these more complex forms, at least to where they can look decent in terms of spacing and chunking. I also think our documentation can be improved to be more clear about spacing around certain parts of forms such as between section headers and various form controls. 

I also wonder if fine tuning our visual hierarchy in terms of things like form input labels and section headers could help here. 

Here are some examples from OpenShift which I think could be improved. I think they could use some work from the product end but also it begs the question of how we can help avoid this from the PatternFly end. 

![image](https://user-images.githubusercontent.com/30935938/108528467-726d5100-72a1-11eb-97d8-2660fad0b2fc.png)
![image](https://user-images.githubusercontent.com/30935938/108528486-78fbc880-72a1-11eb-8d76-6465bc233952.png)
![image](https://user-images.githubusercontent.com/30935938/108528538-84e78a80-72a1-11eb-94fe-d387ada7833c.png)
![image](https://user-images.githubusercontent.com/30935938/108528576-8d3fc580-72a1-11eb-9795-8c7e49dbd132.png)
![image](https://user-images.githubusercontent.com/30935938/108750309-dc3e6280-750e-11eb-8e30-c1542edcca51.png)

@mcarrano @mcoker

**Comment by doruskova** [comment]
@mcarrano @mceledonia Here's the update on form sections. I chose the last two examples from this issue. 
https://marvelapp.com/prototype/g6f5ife/screen/78060220

Example 1 - [version with divider](https://marvelapp.com/prototype/g6f5ife/screen/78060220) and [without divider](https://marvelapp.com/prototype/g6f5ife/screen/78060223)
Example 2 -[ with divider](https://marvelapp.com/prototype/g6f5ife/screen/78060221) and [without divider](https://marvelapp.com/prototype/g6f5ife/screen/78060222)
Design spec [here](https://marvelapp.com/prototype/g6f5ife/screen/78060232)

Not sure if the form with divider doesn't look too heavy. It looks fine when the form is not too complex. On the other hand the section is visually more obvious. The second thing is if the divider does not break the structure when sections follow each other (expandable sections), because it may seem that it does not belong to the first part.

**Comment by mcarrano** [comment]
We did just introduce the ability to create Field Groups (https://www.patternfly.org/v4/components/form#field-groups). These can be expandable or non-expandable. I wonder if we should be using those to help organize content.

**Comment by doruskova** [comment]
@mcarrano Yeah, it's basically the same thing :D So, I think that we should add this screen to our template file because we don't have a real example like this. https://marvelapp.com/prototype/g6f5ife/screen/78060220
Also, I looked at the template file and it looks that I need to update the existing screens because they're a little bit different from the implementation. However, we should emphasize this component more because I think that people don't know about it. I can ask if anyone is using this component and get another example for a template file. 

@mceledonia WDYT?

**Comment by mcarrano** [comment]
You might want to ask @lboehling for an example as I think they were using this in one of the App Services products. Also OpenShift.

**Comment by doruskova** [comment]
@mcarrano Yes!

**Comment by mcoker** [comment]
@mcarrano lgtm

**Comment by doruskova** [comment]
@mcarrano 2 new examples have been added to a template file.

**Comment by mcarrano** [comment]
Thanks @doruskova .

@mcoker do you think it would also be useful to build these out as demos?

**Comment by mcoker** [comment]
@mcarrano I think that would be fine, just to confirm this is just a demo of field groups using more complex content in the groups? We don't currently have a field group demo - only have the component example - so I think that would be a good addition.

**Comment by mcarrano** [comment]
@doruskova Can you repost what is the final design solution for this? I'm a bit confused going through the comments. I can open a core issue then to create a demo.

**Comment by doruskova** [comment]
@mcarrano I've added these two examples https://github.com/patternfly/patternfly-design-kit/issues/384 
to a template file and now we'd like to have them as a demo. So I think that you can open the core issue for it :)

**Comment by mcarrano** [comment]
Thanks @doruskova . I have opened https://github.com/patternfly/patternfly/issues/4148 to begin implementation.
