### ISSUE TITLE
Pagination without total number of items

### ISSUE THREAD

**Issue by edewit** [patternfly/patternfly-design#1025]
In some scenarios it's to expensive to get the total number of items. It would be nice if we could still use the Pagination component without that.

**Comment by mcarrano** [comment]
Need to consider the recommended design solution for this use case. Will add to our roadmap.

**Comment by doruskova** [comment]
@mcarrano I was exploring this issue and here are my thoughts because I'm not sure if I understand this issue correctly: 

1. On a cloud platform we usually use the compact pagination at the top of the table (smaller space) and then full pagination at the bottom [Marvel link](https://marvelapp.com/prototype/cf5fj8i/screen/81372798). That means that you always get a number of items because it says "1-10 of 11" and you can select how many pages you want to show. But you should still see it and be able to get to the end with double arrows. 
2. In that case the bottom pagination looks like this on a mobile. It's pinned to the bottom of the screen and you can browse the content. [Marvel link](https://marvelapp.com/prototype/cf5fj8i/screen/81372797)
3. It's also presented here [here](https://www.patternfly.org/v4/components/pagination/react/sticky) and you can pin the pagination to the top.
4. If the issue is that compact pagination doesn't support double arrow so it's not possible to get to the end right away > then it's something to discuss. But, i'm not sure it this is an issue. 
5. The only issue I noticed was that the top full pagination doesn't behave the same as the bottom one. Is it intentional? Because the sticky pagination can do both. [Marvel link](https://marvelapp.com/prototype/cf5fj8i/screen/81372661)
6. However, I'd use the sticky header or at least full bottom pagination to see number of items in a table and get the responsive behavior on a mobile. 

@edewit Can you expand more your use-case? Did you try to use sticky header or full pagination at the bottom?

**Comment by edewit** [comment]
@doruskova on keycloak we have a list of users these users don't directly from the database but from 3rd party systems so getting the total number of rows is not an option. I now use `toggleTemplate` to remove the total amount, but I still have it displayed on mobile layout.

**Comment by doruskova** [comment]
@edewit So, if I understand correctly. You need pagination without the total number of items and it's difficult because the PF component uses it everywhere and it's not customizable. Is this correct?

**Comment by edewit** [comment]
Exactly it can be configured to not have the total number, but it will show it on mobile.

see:
Normal layout
![image](https://user-images.githubusercontent.com/51133/129005883-9cd98158-4a8b-4f9e-85ad-3f34577968a7.png)
Same page on mobile:
![image](https://user-images.githubusercontent.com/51133/129006110-6694fff9-68e1-48f3-9318-5f21df7fdc31.png)
The `toggleTemplate` attribute is only used for the "normal" layout

**Comment by doruskova** [comment]
@mcarrano It seems more like a technical issue than a design issue. WDYT? Is possible not to show the number of total items on a mobile? Can we tweak the component easily to make this possible?

**Comment by mcarrano** [comment]
@edewit @doruskova I guess that the only design question here is what do we display if we remove the total item count? Just "1-7" in the mobile toolbar example above? Maybe that's the best we can do, but it  feels like that does not give the user much information. Let me know your thoughts. If that's the only solution, then I will pass this over to development to add that as a new variant when it's not possible to fetch a total item count.

**Comment by doruskova** [comment]
@mcarrano Yeah. If we talk about only compact mobile pagination, then I think that it's the only design solution. What about showing only "1 - 10" but keep the arrows (see a screenshot) so that the user can browse the pages? At least for the full bottom pagination to keep any value? Unfortunately, the compact would show only "1-10" at the top.  
![Mobile xs - pagination](https://user-images.githubusercontent.com/32618096/129033280-75140e33-9c1f-421e-97fc-101b0697959c.png)

**Comment by mcarrano** [comment]
The more I think of it, maybe for mobile, we should just hide the upper page count entirely and only have the footer pagination control. What do you think @edewit @doruskova ?

**Comment by doruskova** [comment]
@mcarrano I think it's a great idea! Agree with that.

**Comment by mcarrano** [comment]
@mcoker if we want to just hide the top pagination below the mobile breakpoint, is that a change to the Pagination component or the Toolbar? Would this be considered breaking? If so, I think we should add the option. Let me know your thoughts.

**Comment by mcoker** [comment]
@mcarrano it would be a breaking change, and a change to the toolbar I'm assuming since users may want to show it or use it outside of a toolbar. Though the pagination in the toolbar is in a toolbar item (`<ToolbarItem>` or `.pf-c-toolbar__item`), and toolbar items take a prop to hide/show at various breakpoints. The prop to use here would be `visibility={{ default: 'hidden', sm: 'visible' }}` where `sm` is the breakpoint you want to show. (`sm`, `md`, `lg`, `xl`, `2xl`). If using core, the classes would be `pf-m-hidden pf-m-visible-on-sm`. Will that work? We can update our demos with that, too.

**Comment by mcarrano** [comment]
@mcoker Yes, I think that works if I understand it correctly. So I think that you are saying we can optionally hide the pagination via a prop at mobile breakpoints? What are the next steps on this then? Do I need to then open a core issue to add these classes and update our demos?

**Comment by mcoker** [comment]
@mcarrano yep! You could also open a react issue to update those examples, too.

**Comment by mcarrano** [comment]
An additional idea proposed by @spytec is to substitute the word "many" for the total page count when using the full pagination. That is summarized in #1084 and here:

> Paginated endpoints may sometimes utilize a cursor-based pagination to optimize for performance or simply not show the total count or total pages. While this is good for improving performance, it means we have no way of knowing how many pages there will be
> 
> This poses an issue for the current PF pagination, as all the designs and the React implementation requires count to work properly
> 
> One design I have in mind could remove the total count of entries, and change number of pages to "many": ![image](https://user-images.githubusercontent.com/6598829/130067498-13141823-1819-4395-8c4f-73ec9c2c34ab.png)
> 
> Which for compact looks like this: ![image](https://user-images.githubusercontent.com/6598829/130067689-409cd8f7-4bcc-4c0b-9c30-cbc3dff41ecb.png)

**Comment by mcarrano** [comment]
Following discussion with @mcoker @srambach and @mceledonia we decided to modify this approach slightly. "Many" will now be used in the item count and number of resulting pages will not be reported when the total item count is unknown. So in the example above, it would read:

"1-10 or many" with the page set to show the current page only (no total page count).
