### ISSUE TITLE
Reconsider approach to scrolling horizontal tabs on mobile

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1034]
There have been requests for a different approach to displaying horizontal tabs on mobile devices. Currently, horizontal tabs scroll when they no longer fit within narrow viewports. Usability concerns have been expressed with this. See this issue for example: https://github.com/patternfly/patternfly-design/issues/840

Want to consider alternative approaches like presenting tabs in an overflow menu.

**Comment by garrett** [comment]
Thanks for opening this issue! :tada: 

I'm looking forward with whatever solutions you and others may find.

**Comment by garrett** [comment]
To illustrate, here are some cropped screenshots from a pending PR in Cockpit.

Normal:
![Screenshot_2021-04-21 Netzwerk - garrett Rain(2) - mod](https://user-images.githubusercontent.com/10246/115538934-af06fa00-a29c-11eb-9dc3-2db180578bb4.png)

Same tabs, in mobile:
![Screenshot_2021-04-21 Netzwerk - garrett Rain(3) -  mod](https://user-images.githubusercontent.com/10246/115538947-b3331780-a29c-11eb-854a-1ff161745c2f.png)

There aren't many tabs, but it requires a lot of interaction to see what's available and to switch to it. Imagine doing this multiple times too.

I think this is a case where it's better to have something that might not look optimal, but is more usable... than the other way around. That is, at least in this case, in Cockpit, I'd prefer to have the tabs flow so that they wrap around when space is constrained. Of course, it's not a one-size-fits-all solution, especially when there are a _lot_ of tabs.

**Comment by itsptk** [comment]
OpenShift has interest in something like this as well. There are certain resources that have additional horizontal nav items that vary in number. Generally there are 1-3 but sometimes there can be 10+. There might be other solutions to this particular problem but it seems like some way to represent the overflowed horizontal nav items would be appreciated, in this case even on desktop screen size.

I tried drawing one rough idea I've seen, using the [tertiary nav](https://www.patternfly.org/v4/components/navigation/#tertiary) as an example, where perhaps there could be an icon button (in addition to the tab scrolling) could be used to launch a dropdown with the remaining overflow nav items for easier access than scrolling to them.

![horizontal nav overflow dropdown](https://user-images.githubusercontent.com/54860125/117175076-6f600800-ad9c-11eb-94c9-ef09c5549aea.png)

**Comment by mcarrano** [comment]
Will get this on the roadmap. One potential solution is to take same approach as we use for [jump links](https://www.patternfly.org/v4/components/jump-links/html#expandable-responsive).

**Comment by mcarrano** [comment]
Would this be solved by the implementation of https://github.com/patternfly/patternfly/issues/1625?

**Comment by garrett** [comment]
I think https://github.com/patternfly/patternfly/issues/1625 is solving @itsptk's case.

We're talking about two different concepts for tab overflow though:
1. **Overflow wrapping**: When a smaller, often fixed set of tabs are used for navigation, the tabs could wrap to make it easy to jump between items on smaller screens (especially mobile).
2. **Overflow menu**: Similar to how browsers handle lots of tabs, often used with an unknown amount of tabs, an overflow menu for tabs could appear to access additional tabs. ([The mockup @itsptk made](https://github.com/patternfly/patternfly-design/issues/1034#issuecomment-832833210) is desktop size, with a _lot_ of tabs.) 

Both are overflow solutions, but are needed for different purposes, in different contexts. Application authors would determine which overflow method is best for their use. (These are both in addition to the tab overflow buttons w/ scrolling, of course.)

I think what's talked about in https://github.com/patternfly/patternfly/issues/1625 would probably solve what @itsptk is looking for, but wouldn't help us with Cockpit with smaller screens.

**Comment by mcarrano** [comment]
Thanks @garrett . I will add this to our roadmap for more consideration.

**Comment by doruskova** [comment]
@mcarrano Adding my update on this issue :)

Some ideas for a mobile version: 
- Dropdown on a mobile - [mock](https://marvelapp.com/prototype/hi2b48a/screen/85189104)
- More menu on a mobile - [mock link](https://marvelapp.com/prototype/hi2b48a/screen/85190729)
- Icon menu on a mobile - [mock link](https://marvelapp.com/prototype/hi2b48a/screen/85191227)

However, this issue is also about a desktop version because scrolling through so many tabs or toggle groups can be difficult.

- Here's the interaction with[ "More menu" on a desktop](https://marvelapp.com/prototype/hi2b48a/section/1559742)
- The last thing I wanted to mention is toggle button group [use-case ](https://marvelapp.com/prototype/hi2b48a/screen/85187946)that uses many toggle buttons and [here's ](https://marvelapp.com/prototype/hi2b48a/screen/85188067)the possible solution with "more" menu.

**Comment by mcarrano** [comment]
@doruskova It's great to see these options. I agree that we should have a general approach that can work for lots of things nav items, buttons, chips, etc. Basically it's a horizontal list of buttons that can take different forms. Maybe share this out at a future team meeting and we can compare the different options?

**Comment by doruskova** [comment]
@mcarrano Yes! I put it on the agenda :)

**Comment by mcarrano** [comment]
Thanks for your efforts on this @doruskova . I have opened https://github.com/patternfly/patternfly/issues/4800 to begin implementation.
