### ISSUE TITLE
Clarify responsive state guidelines and examples for Primary-Detail demo

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design#1041]
The Managed Kafka team is looking to add more clarification around the responsive behavior for the primary-detail demo in PF. 

We discussed that we should update the PF guidelines and demos to include:

- an auto-dismissing details drawer when resizing to a smaller viewport (so the screen defaults to the primary view)
- a specific " <- Back to {{Primary Object}}" navigation action to the top left of the details drawer when the drawer becomes full width on mobile view (instead of the existing (x) icon button)
- a minimum details drawer size (Current suggestion is a minimum drawer size of 320px)

@jgiardino let me know if I missed anything here!

**Comment by jgiardino** [comment]
Thanks for capturing this! You covered everything. We did discuss that if we're using an X like we have in a modal, that there should be an affordance that this is an overlay, which the modal has but the drawer does not. But having the X be replaced with a "<- Back to..." link might be cleaner on resize (i.e. I'm not sure how you could transition from a drawer to a modal).

Another thing worth mentioning is the quick start drawer behavior on modal, which I think is out of scope for this issue, but maybe it's an alternate use case to keep in mind. For me, there are use cases between the primary-detail drawer and quick start drawer are very different and require different solutions on modal:
1. primary-detail - Provides a way to access details about an item in a list, and only displays in context of that list. This means that having a modal approach (i.e. overlay) works for this interaction pattern
2. quick start - Provides an additional panel that persists throughout the application. This means that having a modeless approach is required. And on mobile sizes, means that the user needs a way to easily minimize and restore this panel.

**Comment by mcarrano** [comment]
@mcoker please take a look.

**Comment by mcarrano** [comment]
@lboehling @jgiardino We can consider revising/improving the demo and documentation moving forward, but I believe everything here can be implemented today with the current components. Is this something you feel like you have a dependency on?

**Comment by mcarrano** [comment]
@lboehling @jgiardino I looked into this a bit more deeply. All of the behaviors that you are requested would need to be implemented as part of the Drawer component, I believe, since Primary-detial just uses the drawer. Let me try to address each of these requests in turn:

>  an auto-dismissing details drawer when resizing to a smaller viewport (so the screen defaults to the primary view)

I'm reluctant to say that we should always dismiss the drawer when the viewport is resized as this might not be the right answer for every use case. It should be possible to close the drawer programmatically, however. I've opened a React issue here to update the demo: https://github.com/patternfly/patternfly-react/issues/5908

> a specific " <- Back to {{Primary Object}}" navigation action to the top left of the details drawer when the drawer becomes full width on mobile view (instead of the existing (x) icon button)

Again, while I think this makes sense for the current use case, I'm reluctant to change how the drawer behaves in general. Have this come up as a usability problem during actual use? 

> a minimum details drawer size (Current suggestion is a minimum drawer size of 320px)

Looks like the minimum drawer size is settable via a prop here: https://www.patternfly.org/v4/components/drawer#drawerpanelcontent

Regarding the use of the drawer to hold Quickstarts, I can see where that can be a problem on mobile. Do you know who drove this decision? It was not prescribed by PatternFly. We did at once point discuss adding a modeless overlay window, but that does not exist today.

@lboehling If you wanted to make updates to the design documentation, I would support that. Feel free to open an issue in the `patternfly-org` repo.

**Comment by mcarrano** [comment]
@lboehling please see my questions above. Other than fixing the drawer demo, is there any more action that is needed? If not I will close.

**Comment by lboehling** [comment]
Thanks @mcarrano! I just spoke with Jenn and we agree with all of your comments above.  No more action is needed, and we're fine with closing this issue.

From Jenn -- "...as for the quick starts, since those are getting spun up into a separate project, I would also expect that project to manage any updates it might need regarding the drawer design or behavior."

**Comment by mcarrano** [comment]
Thanks @lboehling and @jgiardino . I will close.
