### ISSUE TITLE
Revisit selected states for tiles and cards

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1042]
Tiles and Cards have a similar issue with reflecting a selected state, Currently a blue border is used. However current browser versions also superimpose a blue border to indicate focus. This means that de-selected cards can look selected when they have focus. Need a solution that works for both of these components.

**Comment by mceledonia** [comment]
Looking through the PF documentation on cards and their selected states, it looks like we already offer a solution which solves this problem. The issue seems to be we offer 2 different selected states for multi-select versus single select.

Here it is shown in the design documentation:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/30935938/123660539-c1079a80-d801-11eb-838e-10caa7441db7.png">

To keep things simple, why don't we just align with our multi-select approach for single-select as well? By using an icon instead of worrying about the card styling (border/fill) we avoid conflicting with any browser focus states and their future iterations.

![image](https://user-images.githubusercontent.com/30935938/123660752-ec8a8500-d801-11eb-96e0-5da142476d56.png)

CC @mcarrano @mcoker

**Comment by lboehling** [comment]
Hey @mceledonia! Just wanted to give some background behind the existing single select/bulk select card states. There are a couple product use cases where cards in a primary-detail view (where single selecting a card triggers the details drawer to open) co-exist with a checkbox multi-select for completing bulk actions (such as delete, share, etc.) in the toolbar. The original designs decided to rely on border/fill for single card selection so that both select options (multi/checkbox and single-full card) could be used at once. I can see how having both select states simultaneously might be a relatively uncommon use case, and how it could cause some confusion/design issues. If we go with the more consistent icon approach, maybe it's worth adding some additional design guidelines/alternate solutions for UIs that are currently using both.

**Comment by mcarrano** [comment]
Yes, thanks for reminding us of that @lboehling . I don't think that radio button selection is really the right thing for primary/detail use cases, although it could work for other things. @mceledonia did you consider using a background fill here like we are already doing for Toggle groups? https://www.patternfly.org/v4/components/toggle-group

**Comment by mceledonia** [comment]
Thanks for the context there @lboehling! I can see why this wouldn't be a great solution there. @mcarrano I have tried the background fill and I think it is a solid option. Here's what that looks like, I'm wondering if we should also do the border as well. The border will somewhat conflict with the browser focus state but that might not be a big issue, that is illustrated below:

![image](https://user-images.githubusercontent.com/30935938/123812650-3fc40c80-d8c2-11eb-83fd-557e30f03604.png)

**Comment by mcarrano** [comment]
I'm happy with this. What do you think @lboehling . If we are good with this, I can present at next week's PF design share. I know that you are on PTO @mceledonia .

**Comment by itsptk** [comment]
At the design share there was a questions how OpenShift is using cards for Quick Starts (with Labels, etc,) so I figured I'd include a few screens here. Let me know if there is any other info would be helpful for this issue!

![quickstart](https://user-images.githubusercontent.com/54860125/125639633-be1eddd2-31fc-48d7-aed5-da17c31af5bd.png)
![quickstart_hover](https://user-images.githubusercontent.com/54860125/125639653-3803fbd9-2e54-45df-8ecf-f90512d61d5d.png)
![quickstart_select](https://user-images.githubusercontent.com/54860125/125639661-3f69e8c7-5f9e-4e2e-967e-ba40c4e0163e.png)

**Comment by mcarrano** [comment]
Thanks @itsptk . This is definitely helpful!

@mceledonia we discussed this during today's design share meeting, and I think this OpenShift example would be a great one to focus on since it uses both graphics and labels.

**Comment by mcarrano** [comment]
Another example...

We use cards in the virtualization space when users want to create a vm via the wizard. So when users choose to create Virtual Machine from a template, we surface the templates available in the cards view. 

Please let me know if you have any questions or need any additional examples.
Thanks,

Yifat

![image](https://user-images.githubusercontent.com/6619860/125656807-4c84616d-58fe-49c7-bec5-3a5c478ff568.png)

**Comment by mceledonia** [comment]
@mcarrano I have a new proposal for this which involves a little more interaction, but from a brief conversation with @mcoker it sounds like it shouldn't be an issue.

The idea is that the hover state is a light blue bottom bar, then on selection the bar doubles in height, shifts to our primary blue color, and also shifts the card position up. The card position shift would not push other cards or alter the layout at all. I was exploring other means of indication, and position was one I found particularly interesting.

It is inspired by Twitch's hover state which you can see in action here - [https://www.twitch.tv/directory](https://www.twitch.tv/directory)
I am proposing we only use this effect on selection, rather than on hover as seen in Twitch.

Here's an animated mockup: 
![Card Select Animation Base](https://user-images.githubusercontent.com/30935938/129784165-229d6503-ae80-4a84-80b9-800874119af5.gif)

**Comment by lboehling** [comment]
I really love this solution @mceledonia! I'm thinking this proposal could translate well for our row selection styling in data lists/tables too if we choose to align.

**Comment by doruskova** [comment]
@mceledonia Could you add a spec for this styling so that I can make it available in our Design kit? Thanks!

**Comment by doruskova** [comment]
@mcarrano Is this styling going to replace the current one or do we still want to keep it? Just wondering if we should override the previous style for a selected card or create a new one in Sketch because if anyone used the current style with a blue border on a top and I'll change the current style > it'll change every component using this style. For example, we use the current style for a static card just to highlight the importance of the card in Malware detection app.

**Comment by mcarrano** [comment]
@doruskova I think this is still a TBD. Maybe hold before making any design kit changes just yet.
