### ISSUE TITLE
Compact label

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1048]
Need a compact label variant for use in tables or anyplace where a smaller label is needed. See https://github.com/patternfly/patternfly/issues/4031 for further discussion about this.

cc @katierik

**Comment by mceledonia** [comment]
OpenShift has a need for this with their badges/labeling system which currently uses custom badges where they should be using labels. We are hoping this can be implemented for a refresh of their resource badge styling which is not yet prioritized. 

Since I have some designs for those already I'll paste them here with a quick spec - basically comes down to reducing the spacers/padding and a smaller font size. 

![image](https://user-images.githubusercontent.com/30935938/131702945-14ec4b48-203f-46da-b508-ba52f5864745.png)

CC @mcarrano @gonoraj

**Comment by andybraren** [comment]
Related OpenShift discussion:
https://issues.redhat.com/browse/ODC-5537

**Comment by mcarrano** [comment]
Yes, the intent is that the compact modifier can be applied to any label color or style.
