### ISSUE TITLE
Add new task tracker icon

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design#1059]
For the task tracker demo in #892 , we are proposing to add a new icon within the masthead to be able to indicate tasks are occurring and to open/close the drawer that they live in. All I did was remove the circles from `fas clipboard-list` (https://fontawesome.com/v5.15/icons/clipboard-list?style=solid) and expand the lines to expand more of the width. I'm attaching the icon here. Not sure if this should be fully brought into illustrator -  @bdellasc @mceledonia any thoughts?

[pf-clipboard-list.svg.zip](https://github.com/patternfly/patternfly-design/files/6610974/pf-clipboard-list.svg.zip)

**Comment by mceledonia** [comment]
@gdoyle1 Since you customized the icon, I think we should treat it as a custom PatternFly icon and take it through that process as we normally would. That basically entails getting it into the Icon Exporter sketch file and exporting SVGs at the proper specs for the dev team to add to our library.

@bdellasc has made an extremely helpful and informative guide for this which you can find [here](https://docs.google.com/document/d/1jAUVam02AC74lsEnaSr1rwBB5NfcqcrNjH9ZTYnoUoI/edit?usp=sharing), that being said I've done a few of these lately so I'd be happy to help you if you need it!

**Comment by bdellasc** [comment]
Thanks for the background @gdoyle1 and follow-up! +1 to @mceledonia 's suggestions about next steps!

**Comment by gdoyle1** [comment]
Created the icon and attaching here. Following the directions of the doc, I will also open an issue in the patternfly core repo and attach the file so the icon can be added into the web and desktop font.

[task.svg.zip](https://github.com/patternfly/patternfly-design/files/6672733/task.svg.zip)
