### ISSUE TITLE
Investigate nav styling for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1065]
For dark themed pages, we may want to provide better differentiating between navigation and the content area of the page. Currently navigation and content tend to blend together as can be seen in this screenshot from the OpenShift Dev Console POC.

![Screen Shot 2021-06-30 at 9.47.52 AM.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/5c9bc7b5-b711-454d-b050-badb87b5ff12)

**Comment by mceledonia** [comment]
So far I think this is the most successful version I've come up with:
- Same background color (100) as content
- Border instead of shadow - the use of shadow here is not consistent with our usage guidelines, where shadows are reserved for elements that overlap other elements on the z-axis. 

Going to keep messing around to see if I can find some similar solutions, but this is worth getting some feedback on.

![image](https://user-images.githubusercontent.com/30935938/123995989-df55cd80-d99c-11eb-8dae-0d8dcc62847f.png)
![image](https://user-images.githubusercontent.com/30935938/123996032-e8df3580-d99c-11eb-99d6-b30792e5229f.png)

**Comment by mcarrano** [comment]
@mceledonia I left a couple of comments in Marvel. While I get your point about shadows, I wonder if we should still consider it. I thought it helped create the appropriate separation between the menu and body of the page.

**Comment by mceledonia** [comment]
I agree, and we can always make an exception.

**Comment by mcarrano** [comment]
Looks good. I will close.
