### ISSUE TITLE
Proposal to add timestamp component

### ISSUE THREAD

**Issue by megan-hall** [patternfly/patternfly-design#1094]
[MARVEL MOCKUP
](https://marvelapp.com/project/5998141)

**Goal** 
Document requirements and align on a design that works across product areas to communicate time across our products in a consistent way. 

**Background**
Currently OCP has a custom timestamp component. We would like to propose to contribute this to Patternfly and make any necessary design changes based on current in console feedback as well as feedback from other designers.

**Requirements**
In terms of functionality:
- Relative and absolute time
- read only version
- version with a tooltip to show UTC (or choice reflected in user preferences)
- short and long version based on format (for charts we may want just the time).
- localization and i18n support for internationalization
- What additional requirements do other teams need?

**Feedback we have heard**
- The globe icon currently provides no functionality or value
- The tooltip hover interaction does not work
- The current design does not look like it will provide feedback on hover

**Documents**
- OCP documentation of how this works in the console today ([doc](https://docs.google.com/document/d/1iAlirKETf7iC-sNQt8YpEeJosyJgxj4HufnuvHgH2xA/edit), [spreadsheet](https://docs.google.com/spreadsheets/d/1fxsPRNyXjDHKbb54DfTliHcpJMmQDl_TP8JMPuJEFZw/edit#gid=0))

**Comment by JustinXHale** [comment]
[[Marvel](https://marvelapp.com/prototype/2cf6171g/screen/83867765)]

Who would have thought TIME was such a big issue. I've designed a slight modification to the current timestamp component. After researching I believe a simple underline. I've always toyed with using a few different formatting options, which can be seen in the marvel. 

@mceledonia and I talked to the visual aspects on this component and I believe we came to a happy consensus on the shades of grey on the underline.

**Comment by JustinXHale** [comment]
[Marvel]

Who would have thought TIME was such a big issue. I've designed a slight modification to the current timestamp component. After researching I believe a simple underline. I've always toyed with using a few different formatting options, which can be seen in the marvel.

@mceledonia and I talked to the visual aspects on this component and I believe we came to a happy consensus on the shades of grey on the underline.

**Comment by mcarrano** [comment]
Thanks @JustinXHale . I just have a couple of questions...

We've started to use the dotted underscore as an affordance in other places. Here, for example, is the way we are using this for the progress stepper: https://www.patternfly.org/v4/components/progress-stepper#with-help-popover We should make sure the spacing, etc. is consistent. But it does raise a question about interaction. Here and in the description list the user must click on the item to reveal more info. Looks like for Timestamp the tip is revealed on hover. That's OK I think but it makes me question whether we need at affordance at all. Thoughts @mceledonia ?

Your Marvel doc raises an interesting question about date/time formats. Do you think that the component should support multiple formats (i.e. selected via a prop)? UTC and ISO8601 being two choices. The PatternFly guidelines say to follow the American standard (https://www.patternfly.org/v4/ux-writing/numerics) - maybe a third choice? Do you think that PatternFly can or should enforce a consistent standard via this component?  I'm not sure and potentially needs more discussion. Do we know what different products are using now?

**Comment by nicolethoen** [comment]
I think that the eventual implementation of this component will need to be flexible enough for people to define their own format. No matter what the official recommendation of PF, people are going to have reason - language, available space, etc - to want something other than the official recommendation. 

Another thing I don't know is what types of formats or data people are starting with that they want to display using the timestamp component. Because we might be limited (not knowing a timezone for example) by a timestamp depending on how it was collected. That's another reason we will need flexibility.

Timezones are absolutely a headache... because it's tough to know how they should be displayed if they are being applied. And there are so many timezones and depending on the OS language, they may be named or labelled differently? Unless you are just using offset times like UTC-06:00, but does that mean anything? So far in the PF time picker, we have just avoiding including timezones altogether, so we don't have a solution. 

And lastly, another aspect of this component, which comes coupled with some sort of enforcement of PF standards, should definitely have an opinion on how to format timestamps so that they are readable to screen readers. ISO8601 timestamps are not very readable using a screen reader, are they? I don't know the solution, but the final component will likely need to have an opinion, right?

**Comment by JustinXHale** [comment]
> I think that the eventual implementation of this component will need to be flexible enough for people to define their own format. No matter what the official recommendation of PF, people are going to have reason - language, available space, etc - to want something other than the official recommendation.
> 
> Another thing I don't know is what types of formats or data people are starting with that they want to display using the timestamp component. Because we might be limited (not knowing a timezone for example) by a timestamp depending on how it was collected. That's another reason we will need flexibility.
> 
> Timezones are absolutely a headache... because it's tough to know how they should be displayed if they are being applied. And there are so many timezones and depending on the OS language, they may be named or labelled differently? Unless you are just using offset times like UTC-06:00, but does that mean anything? So far in the PF time picker, we have just avoiding including timezones altogether, so we don't have a solution.
> 
> And lastly, another aspect of this component, which comes coupled with some sort of enforcement of PF standards, should definitely have an opinion on how to format timestamps so that they are readable to screen readers. ISO8601 timestamps are not very readable using a screen reader, are they? I don't know the solution, but the final component will likely need to have an opinion, right?

agreed. as far as accessibility with screen readers, its something i have not looked into, but 100% will, should be easy for me to test too

**Comment by JustinXHale** [comment]
The marvel has been updated @mcarrano .. it is posted at the top of the description

**Comment by mcarrano** [comment]
Thanks for your efforts on the @JustinXHale . I have opened https://github.com/patternfly/patternfly/issues/4801 to move this along to development.
