### ISSUE TITLE
disabled menu item w/ tooltip solution that follows best practices

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-design#1107]
As we begin refactoring the existing dropdown-like components to use the new Menu component, we recognize that there has not been uniform consistency regarding how we handle attaching tooltips on disabled menu items.

There is currently no recommended or implemented solution for the doing this on the new Menu component.

Some existing dropdown-like components are allowing for browser focus on the disabled item, so that it can display the tooltip when a keyboard/screen reader user focuses on the item.

This solution does not follow best practices - tooltips should only be placed on interact-able elements - so a disabled menu item does not indicate to a user that there is a tooltip on it. 

The recommendation is to consider placing a help text icon in a button on the disabled item which can receive browser focus and display the tooltip.

**Comment by mcarrano** [comment]
Per 11/10 discussion, we propose to close and ensure that Menu has consistent behaviors with other components. OK with you, @jessiehuff

**Comment by jessiehuff** [comment]
That's ok with me. I think it makes the most sense to follow the pattern that we came up with for disabled button where it's in a "partially abled state" like in [this PR](https://github.com/patternfly/patternfly-react/pull/3801) and in the docs [here](https://www.patternfly.org/v4/components/button#aria-disabled-button-with-tooltip). I do think it's a little weird that we have examples of static text with a tooltip where I don't know a scenario in which that would be interactive and expected to have a tooltip, but I think a disabled button (and here a menu item) could still be expected using `aria-disabled`. Elements with aria-disabled are interactive in the ways they need to be in order to host a tooltip, by default by allowing click and keypress events (only) and it's configurable further via the agreed upon prop name inoperableEvents (see Button component implementation). I do think tooltips deserve attention though as I've noticed that some of these tooltips on disabled elements in our components aren't working (for example, the tooltip in the disabled dropdown item does not announce in VO).
