### ISSUE TITLE
Define editable label group interactions

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1108]
Currently we lack a standard for performing CRUD interactions on a label group. Users should be able to execute the following interactions on a group. These may be supported together of separately depending on application needs;

* Create a new label (Add label) - This will add a new label to the group. New labels may be created dynamically or constrained to using existing labels.
* Edit an existing label - If supported, the user can edit a label that already exists in the group. Support for editable labels currently exists and is being refined by https://github.com/patternfly/patternfly-design/issues/1073.
* Remove a label - currently supported by clicking the (x) button on an individual label.

For adding new labels, should consider whether and how auto-complete would be supported.

**Comment by mcarrano** [comment]
Some earlier work was done on this here: https://github.com/patternfly/patternfly-design/issues/753

**Comment by mcarrano** [comment]
@pankajshivpuje as discussed, I'm assigning this out to you. We should be addressing the following two scenarios:

* The user can edit and define new labels that are added to a group.
* The user can only choose labels that are already defined in the system (can add and remove but not edit).

Thanks for taking this on.

**Comment by pankajshivpuje** [comment]
Here are the links to the final designs:
[Marvel](https://marvelapp.com/prototype/2d90c04g/screen/85343000)

[Design Document](https://docs.google.com/document/d/1XfP0mgrIrTSUTTClCMl3hvU_CVE14jJmVv-LEOXdfuY/edit#heading=h.ntrodcuix31b)

**Comment by mcarrano** [comment]
Thanks for all your efforts on this @pankajshivpuje .

@doruskova @mmenestr can you review the final designs and open any Sketch kit or doc follow-on issues we need? Thanks.

**Comment by mmenestr** [comment]
https://github.com/patternfly/patternfly-org/issues/2888

**Comment by mmenestr** [comment]
@pankajshivpuje just looking at your final mocks, and wondering if for the second variation (where a user has to pick from a set list of label names), we could have the dropdown come out of the "Add label" label, instead of creating a whole new label from which to choose from. In your current design, there seems to be a weird in-between state where you have a select menu as a label, but the label doesn't actually have any name, so what happens if a user doesn't select anything from the select list? No label is created and there's just an empty select.

On the other hand, if we have the dropdown comes out of the "Add label" button, a new label with a name is immediately created and placed in the label group. It also skips a step and feels more cohesive IMO.

Let me know what you think!

**Comment by mcarrano** [comment]
I agree @mmenestr . This would both clarify the interaction and become easier to implement since the current solution requires us to define a selectable label which is something we don't currently support.

**Comment by pankajshivpuje** [comment]
@mmenestr @mcarrano I was thinking about similar approach before I draw my suggested design. Here are few things to think about:
1. The 'Add Label' button design may look different than what you see in other scenarios. 
2. If user needs to correct a label text/selected value, then user will have to delete the label and go through the process of adding another with the correct text/value.
3. The empty state label is created in other scenarios where user needs to type in the label text. We will need to address if user does not type the text after selecting Add Label. Are there any examples in PF to look for guidance?

I have updated the [Marvel](https://marvelapp.com/prototype/2d90c04g/screen/85343001) based on your suggestion. Let me know your thoughts.

**Comment by mmenestr** [comment]
1. I don't think we necessarily have to change the "Add label" button to a classic dropdown toggle, I think we could probably do a custom implementation or implement the ability to use a label as a dropdown in PF itself. @mcarrano do you agree?
2. There isn't really much room for error in this scenario since they can only select an option from a set list, no? I think it's ok to make them delete and re-select. The effort is super minimal IMO. 
3. I think for scenario 1, the way to address this (and what I thought was already the design, but I think I misunderstood) is that when we create a new label for the user, we should automatically name it something like "New label", and if the user doesn't edit the name, then the label would remain with the text "New label". That way, the label is never empty.
For scenario 2 though, that would be hard to do in your initial design suggestion since they'd have to select from a pre-determined list - and that's why I think we should have the dropdown come out of the "Add label" button.

**Comment by mcarrano** [comment]
> I don't think we necessarily have to change the "Add label" button to a classic dropdown toggle, I think we could probably do a custom implementation or implement the ability to use a label as a dropdown in PF itself. @mcarrano do you agree?

I was thinking something similar. The user would click the "Add label" button and it would open a menu where they could select the label they want to add. This could just be a contextual menu like you would typically get on right-click. After selecting an option, it gets inserted into the group. Yes, there would me no way to change the selection if you picked the wrong item by mistake, but as @mmenestr stated, it would only take a couple of extra clicks to fix this (delete the new label and add a different one).

**Comment by pankajshivpuje** [comment]
Great, thanks for the feedback. I have updated both [Marvel](https://marvelapp.com/prototype/2d90c04g/screen/85343000) and the [design document](https://docs.google.com/document/d/1XfP0mgrIrTSUTTClCMl3hvU_CVE14jJmVv-LEOXdfuY/edit#).

Let me know if anything else is needed to close this issue.

**Comment by mcarrano** [comment]
Thanks @pankajshivpuje . Looks good to me. @mmenestr ?

**Comment by mmenestr** [comment]
I just have one more comment on scenario 1 which I left in the marvel.

Though, for scenario 3, now that i'm looking at it more closely, do we want to explicitly say what the modal should look like with all the options, or are we leaving that up to product teams? Because if we do want to recommend a way of laying it out, I think we should consider making some tweaks to clarify the form and how it would work! (ie: right now there's a checkbox option with filled or unfilled, but it's not clear what checking the box would do - would it create a filled label or an unfilled label?

Here's a potential way we could present it, though not sure it's the best way either - it's definitely a tough one. Let me know your thoughts!

<img width="475" alt="image" src="https://user-images.githubusercontent.com/51165119/160958633-142d2d38-505e-4cf3-b16f-90cadfa5bb9e.png">

**Comment by pankajshivpuje** [comment]
That's good point @mmenestr I feel that we should build in the flexibility in this component and let the product teams decide what works best for them.
[Marvel ](https://marvelapp.com/prototype/2d90c04g/screen/85343000)and [Design doc ](https://docs.google.com/document/d/1XfP0mgrIrTSUTTClCMl3hvU_CVE14jJmVv-LEOXdfuY/edit#)is updated.

**Comment by mmenestr** [comment]
Looks great @pankajshivpuje thanks for making those updates!  @mcarrano should be good to go now!

**Comment by doruskova** [comment]
https://github.com/patternfly/patternfly-design-kit/issues/524
