### ISSUE TITLE
Switch: show both a checkmark and a label

### ISSUE THREAD

**Issue by jgyselov** [patternfly/patternfly-design#1137]
**Describe the issue. What is the expected and unexpected behavior?**

We wanted to add checkmarks to our switches to make them more distinguishable by value when they're disabled. But because our switches already have a label, adding the checkmark isn't currently possible.

![image](https://user-images.githubusercontent.com/87187179/152315523-0b169726-67fd-461e-be36-5bd24db1abf5.png)

We would like to be able to control the appearance of the checkmark regardless if a label is present. Possibly through a variant prop - something like:

```
<Switch isChecked={switchValue} label="Switch with label and checkmark" hasCheckmark={true} />
```

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

CodeSandbox for the screenshot above: https://codesandbox.io/s/unruffled-mendel-cbul6

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Enhancement.

**What is your product and what release version are you targeting?**

Openshift [Assisted Installer](https://github.com/openshift-assisted), no target version.

**Comment by jgyselov** [comment]
Thank you, @mcarrano :pray:

**Comment by doruskova** [comment]
@mcarrano @jgyselov Hey there! I'm adding an update on this issue [here](https://marvelapp.com/prototype/2e2bga6g/screen/85707981)

- I've added an option with a label and checkmark 
- I've changed colors for the switch when it's off and when it's disabled because the disabled state needs to be lighter than it is now. 
- I used a darker color `#8A8D90` (black-500) for an off-switch and `#D2D2D2`(disabled color 200) when it's disabled. The checkmark and the circle element in the disabled state is using `#F5F5F5` (black 150)  

This is how it would look like in a context https://marvelapp.com/prototype/2e2bga6g/screen/85707982

**Comment by mcarrano** [comment]
I think this looks great @doruskova My only question is whether we still need an option with a label and no checkmark. Should we always have a checkmark to emphasize the on state?

**Comment by mcarrano** [comment]
Per design review meeting on Mar 23, we will keep the current options and add a new one to include both a label and checkmark. Opened a new core issue here: https://github.com/patternfly/patternfly/issues/4755  Thanks @doruskova !

**Comment by doruskova** [comment]
@mcarrano Yes! Thanks a lot! I'll open the issue for a design kit.
