### ISSUE TITLE
[Enhancement] - New Icon For Entity Shape - Patternfly/React-Icon

### ISSUE THREAD

**Issue by adithyaakrishna** [patternfly/patternfly-design#1138]
**Describe the issue. What is the expected and unexpected behavior?**
Currently `patternfly/react-icons` does not have the below icon (Entity Icon)  and would really love to see as part of the icons package

<img width="26" alt="Screenshot 2022-02-21 at 10 58 28 PM" src="https://user-images.githubusercontent.com/23498248/155366265-d2148626-035c-4a23-b41c-d675de9bcc20.png">

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Tried using an icon like this, https://codesandbox.io/s/pf-label-mnkpmf?file=/index.js but the label and Icon are getting separated

**Comment by mcarrano** [comment]
@adithyaakrishna can you provide more information about what project you are working on, when this is needed, and some more content (like a screen shot of where this will live or details about the use case).

**Comment by doruskova** [comment]
@mcarrano Currently, we're integrating Insights Advisor recommendations into PCM (Product case management) and we want to use the same labels with icons that reflect Total risk value. We want to make both labels visually consistent for a user because it represents the same thing. However, one of the icons is custom (critical total risk) and it's not available on PatternFly. Would it be possible to add this icon between PF icons? Here's the example in a context. 
Insights Advisor in OpenShift: https://marvelapp.com/prototype/g70a1he/screen/84434999
PCM: https://xd.adobe.com/view/6f4a5d72-3cd4-4c34-a5e1-b9fe20705673-3a19/screen/a69ddf79-8b32-48eb-b0ef-cac81ea77356

cc @adithyaakrishna

**Comment by doruskova** [comment]
@mcarrano I followed the tutorial and created the SVG file. I opened this issue https://github.com/patternfly/patternfly/issues/4747 based on the guide. I need a review that it's good to go so that I can update the Icon exporter and patternfly-icons.zip.
When it comes to a timeframe > sooner is better. 

@adithyaakrishna Do you want to add anything? :)

**Comment by adithyaakrishna** [comment]
@doruskova @mcarrano @mcoker Thank you so much for the new icon 💯 🚀
