### ISSUE TITLE
dropdown and menu items - danger state (for delete / remove actions)

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly-design#1168]
**Is this a new component or an extension of an existing one?**

Existing component would be the dropdown and menu items.

**Describe the feature**

When there's a delete or remove action on a kebab menu, it should communicate that it's a dangerous action.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**

For Cockpit, we have been changing the color of the text. 

We have local overrides for this that look like this:

```scss
.pf-c-dropdown__menu-item.pf-m-danger {
    color: var(--pf-global--danger-color--200);
}
```

However, the background of a hovered icon could (and probably should) change in addition to the text itself.

We might want something like `isDangerous` for the react select item.

**Any other information?**

Color blind red/blue differentiation works for all forms of color blindness. Even full color blindness can determine different shades of luminance. Additionally the color is just an enhancement of the descriptive text to remove or delete.

#### Full color

![blue-red](https://user-images.githubusercontent.com/10246/162959300-6822d803-67a7-4a74-826d-f04fc7366e66.png)

#### Deuteranomaly

Red-green, most common

![deu](https://user-images.githubusercontent.com/10246/162959244-070aeb3d-28f4-45c0-9463-e4900661ce6d.png)

#### Protanomaly

Red-green, less common

![proto](https://user-images.githubusercontent.com/10246/162959236-4a7db710-7f45-4ade-bcb3-b25204496822.png)

#### Tritanopia

Blue-yellow color blindness

![tri](https://user-images.githubusercontent.com/10246/162959970-96a6fb8d-cf93-42eb-a318-ef73d46e2603.png)

#### Monochromacy

Complete color blindness, extremely uncommon

![lumanance](https://user-images.githubusercontent.com/10246/162959298-4ded024c-ad64-4064-9158-d87cfd51866b.png)

**Comment by yichen1yu** [comment]
Examples and possible options: https://marvelapp.com/project/6367752

**Comment by yichen1yu** [comment]
Sketch editable link: https://www.sketch.com/s/82eb6c6a-5ae2-442c-952d-5c0d575f6b06

**Comment by garrett** [comment]
Apologies, but I can't see any of those mockups.

First mockup link:

![image](https://user-images.githubusercontent.com/10246/182887009-a5ae6ee7-39b0-473a-9d28-1ac3e78a25cf.png)

Second mockup link:

![image](https://user-images.githubusercontent.com/10246/182887092-73c518cc-b72b-4178-b207-00c99498f7a6.png)

**Comment by yichen1yu** [comment]
Hi Garrett, could you try this link : https://marvelapp.com/prototype/1803675e

**Comment by garrett** [comment]
Thanks! That's a lot better.

Here's an inline image of both options:

![image](https://user-images.githubusercontent.com/10246/183448598-f70b272a-1d72-4aea-9526-23276db54e33.png)

I think since it is a destructive action, it does make sense to highlight that — therefore I prefer option 2, with its hover state of a red background. As pointed out above in this thread, GitHub basically uses option 2.

**Comment by imjoyjean** [comment]
@garrett thank you for sharing this at the playback today! I like option 2 because it matches the colors for the danger button in PF, as well as how it makes it clear that it is a dangerous action.

**Comment by mceledonia** [comment]
Here's a proposal for option 1 with dark theme as well, a few notes....
- Proposing we suggest to use a divider to separate destructive actions from non destructive actions when they coexist in a menu.
- Our lighter destructive color in dark theme actually wasn't accessible over the background highlight color (which it should be as that is our lightest bg color), so I'm proposing an update to red-8888 in dark theme which is shown in the screen below.
- I'm impartial to option 1 or 2 (agree with @imjoyjean's point above), but leaning towards 1 simply because we don't use a colored background fill as a hover state elsewhere in the system. Also the red text color + mandatory confirmation action should be enough weight to convey they destructive nature of the action. 
  - Not the strongest point, but it is what makes me lean towards keeping it simple. That being said if the majority prefers option 2 I'm ok with that, I don't have a strong preference.

![image](https://user-images.githubusercontent.com/30935938/185442325-e3848af8-d827-4962-8988-b1139a69f72f.png)

**Comment by mcarrano** [comment]
@mmenestr can you open an issue to add design guidelines for this (if you haven't already done so). I think it makes sense for this to be part of the Menu component. Do you agree?

**Comment by mmenestr** [comment]
Yes I agree @mcarrano - opened this issue: https://github.com/patternfly/patternfly-org/issues/3165

**Comment by mcarrano** [comment]
Thanks @mmenestr . Closing the design issue in favor of https://github.com/patternfly/patternfly/issues/5057
