### ISSUE TITLE
Create component illustrations for catalog view [Master ticket]

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1172]
Need to generate illustrations for populating cards per the designs here: https://marvelapp.com/prototype/hjbd30h/screen/86590461

**Comment by maryshak1996** [comment]
@mcarrano I have created this spreadsheet here for the illustrations to be tracked with: https://docs.google.com/spreadsheets/d/15s7JE-yF_fa0DdATZfR6Kty4QY4m8kDIXEbGeiNlvec/edit#gid=0
I'm not sure if Angela, Shayna, and Sylvana are all on GitHub, but I was curious if we should create an issue for reach of them or if we should just have this issue here and track statuses in that spreadsheet?

**Comment by smckinno** [comment]
Here is the final marvel link of all the images! 
https://marvelapp.com/prototype/702eg8i

**Comment by mcarrano** [comment]
Sketch file link: https://www.sketch.com/s/7bec720b-7f77-4f22-99a1-a48735c0b147

Google doc with instructions for creating new illustrations: https://docs.google.com/document/d/16hy-fOLvoiTOpNODrhByX9yr7v45Nq5UsSmX_MeZDBk/edit?usp=sharing

Folder of png images: https://drive.google.com/drive/folders/1HAcKpiRGP4q0ttLXyDoEJhQGnJ0Un0O9?usp=sharing

@maryshak1996 @mmenestr welcome your thoughts on where this information should live and how we should maintain it moving forward when we add new components.
