### ISSUE TITLE
Requesting new toggle button component to trigger drawer

### ISSUE THREAD

**Issue by simrandhaliw** [patternfly/patternfly-design#1173]
### Requirement
The API Designer design team has come across a use case that requires including a count of issues in the toolbar section on the Editor page. This count of issues would trigger a side drawer that lists the issues. The count changes based on whether the user resolved the issue(s) or not.

Currently, there are no PF components that support this use case properly. While exploring some design variations, I created the following mockups for the toggle button.

### Design samples
<img width="639" alt="Screen Shot 2022-06-07 at 11 39 33 AM (1)" src="https://user-images.githubusercontent.com/40873417/173909164-d671b2e2-2c99-4bd5-b076-fd2d4f0c75e1.png">

Mockup link (provides context): https://www.figma.com/proto/BswZf9XbyY1VOTHAdUOUgx/API-Designer?node-id=1952%3A15436&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1952%3A15436

**Comment by mcarrano** [comment]
@mmenestr I see that you placed this on our design sync meeting for tomorrow so just assigning to you for now for follow-up.

**Comment by mcarrano** [comment]
@simrandhaliw I've added this to our feature roadmap. Currently I am scheduling out into Q4, but let me know if you are needing to hit any specific release targets.

**Comment by simrandhaliw** [comment]
Great! Thanks, @mcarrano!

**Comment by simontalusan** [comment]
Here are the links to the proposed design:
Sketch: [https://www.sketch.com/s/de96f297-317d-451b-abcc-8b9a4b87afdc
](url)
Marvel: [https://marvelapp.com/prototype/idfijd4/screens](url)

**Comment by mcarrano** [comment]
Thanks @simontalusan . I have opened https://github.com/patternfly/patternfly/issues/5012 to begin implementation of this. 

@simrandhaliw see the designs attached. After a few iterations, we modified your original designs to use a plain button with a badge to the right. We discussed use of the toggle button as your original design showed, but decided against that as it was primarily intended for use as part of a button group. The plain button with the badge, as shown, provides better differentiation from other toolbar actions. Although I'd like to implement this so that a badge can be added to any button variant. In this case, the button will not retain state, but we felt that was unnecessary since it will be evident to users that the drawer is opened and they can close either by clicking the button again or clicking the drawer's close button. Let me know if you have any questions.
