### ISSUE TITLE
Consider whether we need Chips

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#1222]
Chips and Labels share nearly identical functionality while having unique usage and visual appearance. We should consider whether chips are still needed or if labels can be substituted to satisfy and existing use cases that require chips.

**Comment by mcarrano** [comment]
@mcarrano will pull together more discussion - include Michael, Margot, Tina, Sarah R

**Comment by mcarrano** [comment]
@mmenestr @mceledonia @lboehling @srambach @tiyiprh and I met today to discuss this. The general consensus was that it would be good to deprecate chips in favor of using compact labels instead. @mmenestr will mockup a page with both filter chips and labels so we can see what this would look like. Probably want to constrain the visual appearance of labels used in place of filter chips (i.e. simple gray labels).

It was observed that we don't currently support a true compact label group (label group height is not affected by making labels compact), so this would need to be addressed if we proceed with this update.

**Comment by mmenestr** [comment]
Mocks here: https://www.sketch.com/s/d7e287f4-39e3-4c17-a302-2131d8f3ea87

**Comment by mmenestr** [comment]
**Final proposal/plan:**
We have decided to fully deprecate chips in favor of labels.

This will require the following changes:
- Get rid of the chip and chip group components
- Create a new compact label group component
- Change the standard label group component to match the new compact label group styling
- Update all Filter demos and table demos that include chips in them
- Update [Multiple select component](https://www.patternfly.org/v4/components/select#multiple) to include labels instead of chips inside the toggle

All relevant details and mocks can be found here: https://www.sketch.com/s/d7e287f4-39e3-4c17-a302-2131d8f3ea87

**Comment by mcarrano** [comment]
Thanks @mmenestr ! I have opened the following development issues:

Deprecate the chip and chip group components. Core issue: https://github.com/patternfly/patternfly/issues/5343 ; React issue: https://github.com/patternfly/patternfly-react/issues/8579 

Create a new compact label group component and change the standard label group component to match the new compact label group styling. Core issue: https://github.com/patternfly/patternfly/issues/5344 

Update all Filter demos and table demos that include chips in them. Core issue: https://github.com/patternfly/patternfly/issues/5346 

Update[ Multiple select component](https://www.patternfly.org/v4/components/select#multiple) to include labels instead of chips inside the toggle. Core issue: https://github.com/patternfly/patternfly/issues/5345

**Comment by mmenestr** [comment]
Design doc issue opened: https://github.com/patternfly/patternfly-org/issues/3410

**Comment by lboehling** [comment]
Design kit issue opened: https://github.com/patternfly/patternfly-design-kit/issues/606
