### ISSUE TITLE
Design token documentation

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-design#1258]
As part of the design token work, we should document each token and the intended role/usage. This can live on the core workspace, but should eventually be a page on org.

**Comment by nicolethoen** [comment]
I was talking to @srambach about this issue a little bit this morning.
I think, ultimately, it'd be best to have a json file which exists as the gold source for the design tokens and their values for each theme. 
That json file could be used to build a CSS file for usage in core. It could also be used to populate the tokens and their values in the sketch library. And It could also be used to populate a table or other documentation on the website. 

How it'd be presented on the website will take some intentional design. And I recognize that while @mcoker is working on building out the tokens, he is writing it out initially in CSS as a bunch of CSS or SASS variables. I'm not sure how soon we'd want to convert the initial CSS into a 'gold source' JSON file - likely not something that needs to be done immediately, but would ultimately help with communication and consistence long term.

**Comment by mcoker** [comment]
A popular tool for ^ is https://amzn.github.io/style-dictionary/
