### ISSUE TITLE
Skeleton/empty state graph for Day 0 usage

### ISSUE THREAD

**Issue by tiyiprh** [patternfly/patternfly-design#1278]
## Requesting new features, enhancements, or design changes to PatternFly
- Describe the use cases and requirements of the new feature or enhancement you are requesting.
In Event-Driven Ansible, we show a data graph on the dashboard. However, the graph will only show once a rule is run and there is data. On Day 0, we want to show a skeleton/empty state graph to indicate to the user that there is something that will be shown on the dashboard even though there is no data populated yet. 
- Explain *why* this feature is needed and/or why these requirements cannot be met using existing components.
There is currently no skeleton/empty state graph but examples of skeleton components.
- Link any detailed design documents, rough sketches, wireframes or workflows.
Based on the skeleton component currently in PatternFly, we've designed a possible solution to meet this use case.
<img width="799" alt="Screenshot 2023-11-20 at 12 40 16 PM" src="https://github.com/patternfly/patternfly-design/assets/98424339/a9f2153b-dd1b-4ac6-bebf-a7f4fa67b196">
Mockup: https://www.sketch.com/s/b2f1b675-cfe0-4016-b781-12b589027938/a/OebpAO2

**Comment by andrew-ronaldson** [comment]
In another product I have seen a simple bordered area containing an empty state to build a query. Would something like this work for your use case?
<img width="1427" alt="Screenshot 2023-11-22 at 12 12 04 PM" src="https://github.com/patternfly/patternfly-design/assets/28658548/3d1686ff-a87f-49a7-af71-77caf7942d77">

**Comment by tiyiprh** [comment]
Hi @andrew-ronaldson, thanks for this! This empty state is a step in the right direction from what we had before, which was no empty state at all, but we are hoping to improve upon empty state nuances depending on the type it is. The typical empty state could work in this case but we would like to have something more visually robust to display what the resource will be once it is fully loaded/available. I believe @tiffanynolan has some experience and is working on empty state nuances so maybe she'll have some feedback here as well!

**Comment by tiffanynolan** [comment]
Thanks for the ping, @tiyiprh. While we have not finalized design guideline proposals for this use case, the working group participants were very fond of a an empty state variation that has a blurred background and then a very clear action to create data that would fill in that graph. Something like this:
![image](https://github.com/patternfly/patternfly-design/assets/15326290/b770625c-fdd3-4920-86a5-c4696b1774b7)

**Comment by tiyiprh** [comment]
Made some iterations based on the feedback and then discussed with @tiffanynolan. We came to an agreement on this mockup:
![Graph Empty State](https://github.com/patternfly/patternfly-design/assets/98424339/e89b2817-3ff0-4f83-b6c4-b022f0d3327c)

We are showing a static image with a fixed design based on the type of graph once data has been input and will have a fixed height. Once data has been populated, the height will change accordingly. We are using the [extra small empty state from PF](https://www.patternfly.org/components/empty-state/#extra-small) within the graph area. 

This is just some context of what our generic empty state is like versus what a graph empty state would look like. The graph empty state gives more context on what the user can expect to see versus just the generic empty state.
<img width="839" alt="Generic vs Graph Empty State" src="https://github.com/patternfly/patternfly-design/assets/98424339/24bb78e6-42b9-4455-b13c-61ef3a9441d7">

**Comment by andrew-ronaldson** [comment]
Pinging @dlabrecq on this for his chart expertise. Is this ghosted chart with Empty state technically possible?

**Comment by dlabrecq** [comment]
I spent some time creating a POC to add both PatternFly's `EmptyState` and `Skeleton` components.

**Example 1**

![been run](https://github.com/patternfly/patternfly-design/assets/17481322/252dda09-66e9-4560-8912-899fb2b8c9b9)

It seems possible at first glance; however, I quickly discovered a few issues.

1. The `EmptyState` does not fit in smaller charts. The example above works, but it must be a large chart. I found that the chart must be 300px min, which is 1/3 larger than any of our PatternFly chart examples -- some pie charts are only 50px. 
2. In order to show HTML within an SVG image, we must wrap `EmptyState` by an `foreignObject` tag -- something compatible with SVG. The problem here is that `EmptyState` is no longer responsive as the window shrinks.

**Example 2**
This shows that `EmptyState` it's too big for our typical chart examples. In addition, `EmptyState` is not responsive in an SVG.

https://github.com/patternfly/patternfly-design/assets/17481322/e5a998c5-ccc9-4401-98be-870f85c0ec42

**More issues / notes**

* An empty chart must still have data to show those fake lines in the UX design
* Charts may not accommodate an `EmptyState` at small window sizes
  * `EmptyState` not likely to be responsive within in an SVG
* Not all charts have an axis, grid lines, same legend layouts, etc.
* What about pie charts, bullet charts, etc., what would that look like?
* Charts are composable, so there will be multiple components to override
* `EmptyState` is also composable and would be added to `Chart` separately, similar to `ChartLine`, `ChartAxis`, etc.
* `EmptyState` must be wrapped by foreignObject
* `Skeleton` must be wrapped by foreignObject

That said, this could just be a simple PatternFly EmptyState with a background image. At least that would be responsive.

**Comment by tiyiprh** [comment]
Thanks so much @dlabrecq for taking the time to work through this and the feedback. Based on the above, we reworked the design. 
Our thought is to separate out the skeleton view and use a plain alert instead as the "empty state" warning, including description. This way, regardless of the chart type and size, we can still display a skeleton view and have the alert with description and action within the card. This will also scale better.
![Rule Audit Graph2](https://github.com/patternfly/patternfly-design/assets/98424339/fe4d2414-5b78-4805-8785-139433970e3b)
![Dashboard-Day0UpdatedGraph](https://github.com/patternfly/patternfly-design/assets/98424339/0068ca74-f255-49b0-83aa-cbb1aad768ce)

**Comment by dlabrecq** [comment]
Curious what would a skeleton look like for other types of charts; bar, pie, donut, utilization, bullet, area, etc?

**Comment by tiyiprh** [comment]
I'm thinking something like [this](https://www.figma.com/proto/N7hImgEN8rnyKmkz34wcuP/PF---Skeleton-charts?page-id=0%3A1&type=design&node-id=2-372&viewport=328%2C398%2C0.07&t=iYlJZWG8k9Di231C-1&scaling=scale-down&mode=design)? Let me know any feedback!

**Comment by dlabrecq** [comment]
Are you looking for us to use the animated PatternFly skeletons as the grey boxes?

The threshold chart looks a little tricky with the dashed lines -- all other chart legend symbols are grey boxes.

I think most of the mocks are doable. Don't know if I could match each chart exactly, but would be close. 

The charts also need data in order to plot those fake lines. So, it's not clear if users would need to override the chart themselves? 

The gray boxes are positioned absolutely and may need to be adjusted slightly by the user. Will need another POC to figure all that out.

**Comment by tiyiprh** [comment]
We are planning to use grey boxes and not the animated PF skeletons.
For the threshold chart legend, I used whatever the PF example was. If it needs to use a grey box, that's fine with us.
We weren't planning to use real data but just wanted to show a static example chart type based on whatever the chart will be when it's populated.

**Comment by dlabrecq** [comment]
Ok, just wondering if the chart was expected to provide fake data. It could provide something basic, but probably wouldn't be a true representation of the populated chart.

**Comment by tiyiprh** [comment]
Something basic is fine. The idea is just to show the user an example of what the chart/graph would look like as a placeholder until it gets populated and filled out so they have an idea of what they can expect to see.

**Comment by dlabrecq** [comment]
I created a draft PR here https://github.com/patternfly/patternfly-react/pull/10311

Developers can provide their own fake data to represent their graphs. Or, copy the examples provided.

You can view live examples below 
https://patternfly-react-pr-10311.surge.sh/charts/skeletons

**Comment by andrew-ronaldson** [comment]
Closed with react [issue](https://github.com/patternfly/patternfly-react/pull/10311) and design kit [issue](https://github.com/patternfly/patternfly-design-kit/issues/733)
