### ISSUE TITLE
Scrollbar - transparent track

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-design#1315]
The corners of the scroll bar look odd beside the rounded corner of page sections. 

![Screenshot 2024-05-29 at 4 57 39 PM](https://github.com/patternfly/patternfly/assets/26305082/50a888e9-da81-4686-9d88-2c3f0f8d096b)

![Screenshot 2024-05-29 at 4 57 31 PM](https://github.com/patternfly/patternfly/assets/26305082/f15a14ac-e4ab-4700-8e96-5c7cc38e104c)

It doesn't seem we are updating the color of the scrollbar in dark theme like we were in PF5. Were we using `color-theme: dark` or something similar before that we are no longer using?

We could update the track color of the scrollbar using css `scrollbar-color`. This issue is especially obvious in Fedora machines.
We should also check the browser compatibility of the scrollbar-color style.

**Comment by lboehling** [comment]
Design refinements to improve scrollbar appearances in v6:
 
Here are several [hopefully small] adjustments to our page/sidebar components that should help with the appearance of scrollbars in v6:   

- [Transparent track as mentioned above if possible]
- Reduce the page border radius to border—radius—medium so the curve doesn't look as awkward cutting off the scrollbar. Placing within an element that can get a border radius might still help here @mcoker)
- Reduce the border around the content area to global—spacer—xs, 4px(it was 8px before)
- Adjust the nav scrollbar to have padding to its right so that it is centered between left nav and page body

With adjustments listed above: 
![image](https://github.com/user-attachments/assets/67774f53-917c-4093-93de-89328caa8e1d)

Current state: 
![image](https://github.com/user-attachments/assets/cbf0a80f-d634-4701-8318-1d52e1e436dd)


These adjustments should also help https://github.com/patternfly/patternfly/issues/6834

Wdyt @nicolethoen @andrew-ronaldson @mcoker @thatblindgeye?

**Comment by mcoker** [comment]
@lboehling nice! Put those together along with the scrollbar thumb/track update in https://github.com/patternfly/patternfly/pull/7068.

I set the scrollbar thumb color to our border--color--default token, and set the track to transparent, and am only applying those styles to the main container and sidebar. Other things that scroll don't have that update, but could.

FWIW here's a screenshot _without_ the scrollbar color updates, if you want to see what that looks like. 

<img width="2027" alt="Screenshot 2024-09-11 at 8 39 43 PM" src="https://github.com/user-attachments/assets/1b28787f-9f05-441f-a0e4-f70cab4355f9">

**Comment by mcoker** [comment]
@lboehling with https://github.com/patternfly/patternfly/pull/7101, can we close this issue?

**Comment by andrew-ronaldson** [comment]
Closed by https://github.com/patternfly/patternfly/pull/7101
