### ISSUE TITLE
Update small inconsistencies in filter design documentation

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#246]
In the Overview section of the Filter design documentation (http://www.patternfly.org/pattern-library/forms-and-controls/filter/#/overview) there are inconsistencies with reference to "Data Toolbar", the usage of ":" in the low fidelity mocks & capitalization style of the default text in the filter query field.
1 - Data Toolbar has been renamed to Toolbar and should be updated
2 - In the low fidelity mockup in the Overview tab, the Attribute selector includes a ":" after the field name, but it is not in the high fidelity mockup
3 - In the low fidelity mockups in the Design tab, the Attribute selectors include a ":" after the field names.
4 - In the low fidelity mockups in the Overview page, there are 2 mocks each using different capitalization style.  Also need to know if ellipses are suggested ( they are inconsistent in the 2 mocks too)  There are also examples on the Design tag.
My suggestion would be sentence style, but if filtering by a specific field attribute, that attribute is considered a proper noun.  So in the case on the Overview page, "Filter by Name" would be correct.
but if you were allowing to filter by a string match on a number of fields, that may be "Filter by keyword".

**Comment by suzannehillman** [comment]
Hi, I'm a little uncertain what the correct thing to do for this bug is. 

For 2 and 3, do you not want ":" there?

And where would I go to find out the preference for what to do with the caps and ellipses? I'd imagine we must have somewhere to decide these things. :)

**Comment by LHinson** [comment]
@suzannehillman 
- You can view recommendations for capitalization on the terminology and wording page found here: http://www.patternfly.org/styles/terminology-and-wording/ (do a find for "capitalization" and it will take you to the correct section)
- Correct, remove the ":" for 2 and 3
- Terminology and wording says to use an ellipsis (...) to indicate that text is truncated. In this case, it's not truncated therefore there should be no "..."

Let me know if you have any other questions!

**Comment by suzannehillman** [comment]
I'm not sure of the best software to edit png files with; I haven't really had to do that much yet. I'm likely going to try using inkscape without any guidance, though.

Also, I investigated further on input hints (I think that's what the 'filter by name' thing is called?), and I agree on sentence style in general. 

I'm a little concerned by the idea of having two (apparently) different capitalization formats based on name vs keyword, and I'm not completely clear on why one might want to capitalize "name" or other attributes. I understand that they are considered proper nouns, although I'm not entirely certain why. I feel like if we do that, then it'll look weird.

Any guidance here on why we might want to do that would be appreciated!

**Comment by LHinson** [comment]
@suzannehillman good question. I don't find it odd to make the labels capitalized vs the syntax or inline hints because the hints are sentence-y :P I do recognize this as a ridiculous reason though! lol. Would you be interested in researching this a bit more? After talking with @essjaysee, she recommended checking out MSFT style guide

**Comment by suzannehillman** [comment]
@LHinson I'm not actually confused by headline vs sentence. I'm confused by why "Name" is a proper noun and "keyword" isn't, and more importantly by the fact that if we capitalize "Name" within the inline hint and not "keyword" it'll look weird and may confuse people.

**Comment by serenamarie125** [comment]
@suzannehillman IMO Name is a proper noun in this case because it's a field name.  "keyword" indicates that it is matching a keyword to any of the fields, thus not a proper noun.  hth!

**Comment by LHinson** [comment]
I agree that it's odd to have "Filter by Name" and "Filter by keyword" I think we need a rule / definition to help address this concern. @suzannehillman have you research how other style guides approach this?

**Comment by suzannehillman** [comment]
Hi @Lhinson,

I haven't been able to find a lot of information on how people define
proper nouns in the context of things like 'Name' vs 'keyword'.
Nor have I found much on the preferred choice to make in the kind of
situation where sentences should have proper nouns capitalized, but doing
it would make the interface look weird when you also have the possibility
of no proper noun in an otherwise identical situation.

Any thoughts or suggestions on where I might look for information on either
of these?


On Apr 7, 2017 10:20 PM, "Leslie" <notifications@github.com> wrote:

I agree that it's odd to have "Filter by Name" and "Filter by keyword" I
think we need a rule / definition to help address this concern.
@suzannehillman <https://github.com/suzannehillman> have you research how
other style guides approach this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/patternfly/patternfly-design/issues/246#issuecomment-292626561>,
or mute the thread

**Comment by suzannehillman** [comment]
Hi again @LHinson:

I think the sticking point is the idea of 'Name' or some other UI element being a proper noun.

Does anyone know where that idea came from, or if there is some source for that belief? I'm not really finding anything anywhere saying that UI elements are proper nouns, and if that is not the case, then the confusion gets cleared up quickly enough.

**Comment by suzannehillman** [comment]
The best definition I've found so far to explain this is at [UXmatters](http://www.uxmatters.com/about-us/uxmatters-style-guide.php):  

"Follow the capitalization conventions specific applications use—for example, case-sensitive keywords—as well as those for product and feature names—for example, names with internal capitalization like _LinkedIn_. However, be conservative in capitalizing the names of product features and technologies. Capitalize such a name _only_ if there is a marketing or branding campaign for the name, it’s necessary to distinguish a specific component or product such as _SQL Server_ from a technology with a similar name, such as an _SQL database server_, or an industry-standard term is capitalized.

Do _not_ overuse capitalization. Use lowercase unless there is a specific reason for capitalization."

My impression is that the attribute 'Name' (and others) is capitalized because of title caps, not because it's a proper noun.

**Comment by LHinson** [comment]
First, there is many ways to skin a cat. It's always interesting to get into these discussions on how to best approach these things. 

@suzannehillman thank you for doing all this research. I agree with the you. To add to your point... 

Our current style guide defines that "Name" should be capitalized because if it is a "label". It specifics that Tooltips should use sentence style capitalization. I think syntax or input hints is similar to tooltips and should also use sentence style capitalization. 

Additionally, I think the rule is much more clear when we define the rule in association to where it is located. Creating definitions with exceptions makes things more complicated and I don't think we really gain anything with the added complexity. Therefore, I would recommend that we proceed with a rule that's clear and simple for easier application. 

@serenamarie125 Please let me know if you have any concerns with this approach. 

FYI @mcarrano @essjaysee

**Comment by suzannehillman** [comment]
@LHinson, to make sure that I follow: 

1) Name (and others) are capitalized because they are labels which are themselves title caps in the style guide.

2) Tooltips are defined as sentence style caps in the style guide, and we think that syntax and input hints are similar enough to also belong as sentence style caps.

And yes, I absolutely prefer clear and simple over lots of exceptions! :)

I'm likely to start trying to adjust the text in those PNG files this week, and will initially assume that there are no unexpected proper nouns. I'll check this to be sure before submitting anything!

**Comment by suzannehillman** [comment]
@LHinson Another quick question: how closely should I be matching the dimensions of new PNG files as compared to old ones?

**Comment by LHinson** [comment]
@suzannehillman yep, your re-cap is accurate and in line with my thinking! 

As for he dimensions, what's the reason for changing the dimensions? Want to make sure I understand either the problem you are solving or the challenges that you are running up against that would result in a different png size.

**Comment by suzannehillman** [comment]
@LHinson When I used Inkscape to replace the text on the PNG, and then exported the adjusted file as PNG, the dimensions were larger than the previous PNG files. I was unsure if I should be telling Inkscape to export to the same or approximately the same dimensions (if that's even possible, but it seems likely to be possible).

**Comment by LHinson** [comment]
@suzannehillman It doesn't have to be exact by any means but I would try and match as closely as possible. If you would like, you can go ahead and send a PR so I can review. That way I can see what you are talking about.

**Comment by suzannehillman** [comment]
@LHinson, well I'm now very confused. I didn't think that I had actually committed my pull request, but 'create pull request' shows me a website with no available changes. Last time I had done that and not actually submitted, there were all my files showing up and the png file size differences (which is why I noticed). Can you tell if that actually got pushed? It shows up above in this bug as fixes for bug #246, and looking there appears to only let me add comments.

**Comment by LHinson** [comment]
@suzannehillman Let's talk on Friday at 10 am and we will get it sorted out :)

**Comment by suzannehillman** [comment]
This appears to have been inadvertently submitted along with issue #252. I clearly need to be using multiple branches, and will do so in the future.

**Comment by mcarrano** [comment]
@LHinson do you know that status of this?  Should this issue be closed or is there still work to do here?

**Comment by LHinson** [comment]
http://www.patternfly.org/pattern-library/forms-and-controls/filter/#/overview 
> 1 - Data Toolbar has been renamed to Toolbar and should be updated
This issue  has been addressed. 

>2 - In the low fidelity mockup in the Overview tab, the Attribute selector includes a ":" after the field name, but it is not in the high fidelity mockup
This issue has been addressed. 

>3 - In the low fidelity mockups in the Design tab, the Attribute selectors include a ":" after the field names.
This issue has been addressed. 

>4 - In the low fidelity mockups in the Overview page, there are 2 mocks each using different capitalization style. Also need to know if ellipses are suggested ( they are inconsistent in the 2 mocks too) There are also examples on the Design tag.
This is not addressed. The following actions are required: 
* Review the following approach with stakeholders including @serenamarie125
  * Name (and others) are capitalized because they are labels which are themselves title caps in the style guide.
  * Tooltips are defined as sentence style caps in the style guide, and we think that syntax and input hints are similar enough to also belong as sentence style caps. 
* If the above rule is ok, this requires updated mock-ups to update to sentence style capitalization. 
* T&W page should be updated to include this rule about sentence style capitalization for syntax hints.

**Comment by mcarrano** [comment]
I will queue this up for UXS review to confirm this direction forward as proposed above.

**Comment by LHinson** [comment]
@serenamarie125 please review following approach and let us know if there is any concerns. I'm also going to ask Sj for guidance here. 

- Name (and others) are capitalized because they are labels which are themselves title caps in the style guide.
- Tooltips are defined as sentence style caps in the style guide, and we think that syntax and input hints are similar enough to also belong as sentence style caps.

If the above rule is ok, this requires updated mock-ups to update to sentence style capitalization.
T&W page should be updated to include this rule about sentence style capitalization for syntax hints.

**Comment by Essjaysee** [comment]
These approaches seem sensible, given the other guidelines have and the legacy styles we've seen in our own products (and, in my experience, many other enterprise IT products).  

Hints are often written as sentence fragments, so I agree with the capitalization style, and we might also want to include that they don't require a period.

**Comment by LHinson** [comment]
@mcarrano let's review this in the next UXS Lead meeting

**Comment by mcarrano** [comment]
Work in progress as https://patternfly.atlassian.net/browse/PTNFLY-2583 (Update Filter pattern) and https://patternfly.atlassian.net/browse/PTNFLY-2584 (Update terminology and wording.

**Comment by LHinson** [comment]
Jira story 2584 is completed and site has been updated http://www.patternfly.org/styles/terminology-and-wording/#capitalization

**Comment by mcarrano** [comment]
All PRs have been merged. Verify changes on website before closing.

**Comment by mcarrano** [comment]
This is all set. Will Close. Thanks, @zhutaoredhat .

**Comment by zhutaoredhat** [comment]
@mcarrano No problem~
