### ISSUE TITLE
Modal Overlay Panel

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#328]
-- Overview --

Use Cases:

References: OSUX-18 (https://patternfly.atlassian.net/browse/OSUX-18)

Products: OpenShift, OpenShift.io

Scope of work:

Stakeholders/Reviewers: @serenamarie125, @mcarrano, @Mgranfie

Other Info:

**Comment by catrobson** [comment]
@serenamarie125 would you be OK with the OSIO team picking up this contribution?  We'll start by gathering requirements and making sure that the Pattern we create does cover each of our use cases before creating any designs.

**Comment by serenamarie125** [comment]
@catrobson, we already have use cases and matching implementation.  Does it make more sense for me to prioritize having @beanh66 do this later this week?

**Comment by catrobson** [comment]
No, it's not a rush.  I was just looking for something that Laura Wright could contribute to introduce her to the contribution process.  We can look for something else.

**Comment by mcarrano** [comment]
Whoever does this, feel like the first step should be to share the use cases and make sure we have agreement.

**Comment by Mgranfie** [comment]
If Laura takes this up, I would like to capture her experience... so please
lmk. Thanks!

**Comment by beanh66** [comment]
@catrobson @Mgranfie @mcarrano I have a working doc with use cases from the OpenShift perspective. It would be good to be sure we have the OSIO feedback/ use cases covered, as well as any other products. I can finish that up and send that doc out by the end of the day for review if that works?

**Comment by mcarrano** [comment]
Works for me, @beanh66

**Comment by Mgranfie** [comment]
Sounds good, works for me too!

**Comment by beanh66** [comment]
@serenamarie125 @catrobson @mcarrano @Mgranfie Here is the doc for the [Overlay Panel design](https://docs.google.com/document/d/1p03UVQ7NzDtsIneitoeXRmIPzF0aodSMVgfxZiAqgfU/edit#)

**Comment by beanh66** [comment]
@Mgranfie @mcarrano @catrobson @serenamarie125 Thanks for the feedback, I received a number of comments in the design/ requirements doc and I tried to respond to them all by now. Wondering what the best next steps are here since the PF design/dev review doesn't appear to be happening next week.

In the doc, I treated this as a generic pattern with the following options/variations for the Panel:
- Slide in from the top
- Slide in from the right
- Long or short panel
- Narrow or wide panel
- Modal-like characteristics
- Non-modal characteristics 

Are you okay with that approach? If not, do we need to meet to break this into multiple patterns, or what are your thoughts? Let me know what you have in mind for next steps. Thanks!

**Comment by mcarrano** [comment]
Per our discussion, @beanh66 I'd like to propose that we have two new patterns.
1- Modal Overlay that I think addresses most OSUX requirements.  This should consider either the slide-down panel or modal window and when to use one or the other.
2- Modeless Overlay which sounds more like what OSIO is using.  (perhaps Laura can contribute this?)

I think that keeping these separate makes sense as they address distinct use cases, even if some of the implementation is similar.  @serenamarie125 @catrobson @Mgranfie any issues with that?

**Comment by beanh66** [comment]
Works for me @mcarrano 👍

**Comment by mcarrano** [comment]
PR has been merged. Verify changes correctly display on site before closing.

**Comment by mcarrano** [comment]
Verified. Will close.
