### ISSUE TITLE
Need a Select/Unselect All capability for all view types

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#341]
Need a Select/Unselect All mechanism throughout view types (List View, Card View & Table View) when checkbox selection in enabled

**Comment by mcarrano** [comment]
Related issue: #342

**Comment by mcarrano** [comment]
See earlier research on pagination and selection in content views here: https://blog.patternfly.org/pagination-in-patternfly-second-round-cafeteria-testing/

**Comment by serenamarie125** [comment]
I've worked up a couple of options which are more in line with Google Mail

Option #1 - simple dropdown checkbox, interacting with the checkbox will either select all or deselect all .  Selecting the dropdown will provide options ( All & None by default, but other optional filters could be added such as a state - Running VMs, for instance in RHV - or Unread emails in Gmail )
![select dropdown1](https://user-images.githubusercontent.com/12504403/35309475-ba5d3526-007a-11e8-8257-65f72dc5e749.png)
![select dropdown2](https://user-images.githubusercontent.com/12504403/35309477-bc9cb79e-007a-11e8-8562-3004e4122e62.png)
![select - all selected](https://user-images.githubusercontent.com/12504403/35309481-c023628c-007a-11e8-8dda-5c94f4826009.png)

Option #2 - simple checkbox, which will either select all or deselect all 
![select checkbox](https://user-images.githubusercontent.com/12504403/35309556-17263294-007b-11e8-9194-ed01728b5d6b.png)
![select checkbox - all selected](https://user-images.githubusercontent.com/12504403/35309561-1af833e0-007b-11e8-8889-babc40c62e7e.png)

Would be interested to see if this is more in line with what @maryclarke and @jeperry were thinking?  @mcarrano could we include this in the agenda for this weeks PF Design/UXS meeting ?

**Comment by Mgranfie** [comment]
These look great Serena! I'm not sure on Jeremy and Mary's line of
thought... tossing in a couple of points.

1. Singular check boxes without some type of feedback typically are not
well understood, so Option 1 would be the better choice in the sense that
the drop down text confirms, for the user, what exactly is being selected
by clicking on the checkbox.

2. The only question I have for both of these is around how many is "All"
and will a number be returned in the case that it does not select any items
not on the page or would the text in the drop down help to clarify the
number of items selected? Not sure the "Results' text is meant to function
like that?

Will be great to have this !!
Thanks,
Monica

**Comment by maryclarke** [comment]
Although I generally agree that singular checkboxes aren't usually good, I do think it is a well understood pattern in this case.  I also am not crazy about dropdowns that have only the two very obvious options related to the checkbox.  I don't have a really strong opinion one way or the other, but I would vote for option 2 in this case.  Although, if we feel that more options could be added to this dropdown, then maybe it would make sense to have it.

I would agree that it would be good to have some indication of how many items were selected so that in the case of pagination, it is clear whether content on other pages was also selected or not.

**Comment by Mgranfie** [comment]
I agree with Mary that a checkbox with a tooltip and feedback on the
selection numbers, with pagination would work...

**Comment by mcarrano** [comment]
Thanks for posting this @serenamarie125 . This is the approach that Google has taken and seems consistent with what users called for in the usability test that was done last year (see link above). I prefer the overall approach that is expressed in Option 1 since while the dropdown options are redundant, it makes it clear what's happening here and allows use of either the menu or checkbox. The checkbox by itself can be a bit mysterious since it's separated from the list by the filter bar. 

We definitely still need to consider how this plays with pagination and how to reflect selection, filtering, and pagination together at once. I will definitely queue this up for more discussion at this week's PF-UXS meeting.

**Comment by mcarrano** [comment]
Per PF-UXS meeting on Jan 25, will proceed forward with Option 1 approach. I have created https://patternfly.atlassian.net/browse/PTNFLY-2735 and assigned it to myself to explore how this plays with pagination and filtering for reporting items selected in view.

**Comment by mcarrano** [comment]
I've taken @serenamarie125 's mockups a step further to explore what this looks like if we add filtering and pagination. Here's what that looks like...
![screen shot 2018-02-01 at 10 59 22 am](https://user-images.githubusercontent.com/6619860/35688685-b8ccdd44-073f-11e8-847a-eddcb0ddf2f1.png)

I have 2 issues or concerns:

1. Not sure how best to report selection. An earlier design (that did not test well) had this on the right grouped with the pagination control. Now that we are moving selection to the left I feel like this should move, too. Also, if nothing selected, do we report "0 selected" or just hide the text. Doing the later might make things following it jump around.

2. I like having pagination persist at the top right of the second toolbar row, but unclear what happens when you apply many filters. Does this wrap? Do filters truncate somehow?

We can discuss further at today's PF-UXS meeting.

**Comment by maryclarke** [comment]
My thoughts on this design and your issues/concerns @mcarrano:

- overall, I think this is the right direction
- because of filtering changes, etc., the stuff to the right of the selection text will already be moving around.  I would be ok with either approach of keeping 0 selected or by removing the selection text all together
- I like the pagination at the top right as well and think we should truncate the filters when there are too many by having an indication of 'x more criteria' that can pop up an additional list or maybe expand section down to show the full wrapped list.

Just my thoughts

**Comment by Mgranfie** [comment]
My feedback here...

1. I am OK with the selection text going away. If there is a use case to know the total items in the list, these could toggle when items are selected.
2. I am not sure what is in progress with the positioning of the filters, but a wrap and stack might work, it would be my first thought. The behavior of the filters seems to need more thought? Truncating would seem to require a way to see what filters you have set without having to close and open those that are visible...
3. My only question is the proximity of the select all drop down to that column and the numeric feedback is spacious and am wondering if this is a limitation we are working with in or if we are entertaining any movement for those elements?

These are great refinement conversations!

**Comment by jeperry** [comment]
- I also think its fine if selection text is not shown if 0
- I think we should address the filter wrap/stack as a separate issue. I agree it needs more thought but there are some good options already here and it seems easily resolved around these other decisons, I just think we should compartmentalize our work.

**Comment by jeperry** [comment]
I would suggest referring to this feature as **Bulk Selection** moving forward. Since it refers not only to 'select all', but also selecting pre-defined sets of items. And, brevity FTW.

**Comment by Mgranfie** [comment]
Great suggestion Jeremy +1

**Comment by serenamarie125** [comment]
After talking to @mcarrano, we are proposing that "Bulk Selection" will be an optional feature of the [toolbar pattern](http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/), and documented there.  Additionally, the content views should link back to this Bulk Selection feature.
@catrobson @maryclarke do you support this suggestion?
@Mgranfie @jeperry @LHinson FYI 

Additionally, @mcarrano is talking about consolidating other toolbar features to be accessed via the toolbar pattern as well, but that will be documented in a different Issue.

**Comment by maryclarke** [comment]
That sounds reasonable to me @serenamarie125

**Comment by catrobson** [comment]
Sounds good to me too @serenamarie125

**Comment by serenamarie125** [comment]
@mcarrano finally have a draft in a Doc : https://docs.google.com/document/d/1gtDUMASD2dc8G2A82i0lYBjaSxFBw34-65TuilDQjHQ/edit
Need to get some visuals help this week.  Once the text is reviewed, I'll put up the MD.
