### ISSUE TITLE
Filter Panel with Faceted Filter

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#348]
Create a new faceted filter PatternFly Design pattern, documenting design and interaction for the following use case / requirements:

- Users should be able to filter a page with faceted filters
- Faceted filters should not be combined with simple filters

First version of faceted filtering should support :
- a single text field
- one or more categories including multiple filter values

**Comment by Mgranfie** [comment]
Why would a user need these instead of a simple filter?... what problem
does this solve or requirement does this fulfill, that the current
filtering does not?

This is not clear to me... any insight would be helpful.
Thanks!

**Comment by cshinn** [comment]
@Mgranfie: A faceted filter is better than our simple filter pattern for situations where the filter attributes are primarily ones with several distinct choices (publisher, or support level) rather than open-ended fields (name, date created, number of items). Being able to select check boxes rather than putting these in short dropdowns is easier.

Additionally, in pages such as catalogs where a user may not be very familiar with all the options available to them, being able to see the choices laid out at once may help them find what they are looking for.

**Comment by mcarrano** [comment]
@cshinn @serenamarie125 I have flagged this issue for 'requirements review'. As I know this can be a complex problem, I think it would be a good idea to share an initial concept for general review and discussion. Is there something rough you can share on this?

**Comment by Mgranfie** [comment]
+1 on that idea Matt...

**Comment by serenamarie125** [comment]
So i think that my initial "Issue" was probably stated incorrectly, it's more for a need for a filter panel rather than a filter bar, and that the initial design pattern would be that it should support :

- a single text field
- one or more categories including multiple filter values

Does that make more sense @Mgranfie @mcarrano ?  IF so I can update the initial issue text :)

**Comment by cshinn** [comment]
It seems to me that the most contentious and important issue here is the behavior of the filters rather than the appearance, so I think it's worth discussing the specifics here. These are the primary guidelines that I was planning on laying out in the documentation:
## Filter Behavior
- Filters between categories should be combined with a boolean AND operator (items must satisfy both to be shown)
- Filters within a category should be combined with a boolean OR operator (items that satisfy any will be shown)
- If possible, items that satisfy a higher number of filters should be shown higher up the page

Are there specific problems with aspects of these guidelines? If so, what do you recommend instead?

**Comment by ncameronbritt** [comment]
IMHO it's a little tough to boil down the behavior of the ANDs and ORs within a category to a single, simple rule. It depends on context.

If the items in a category are exclusive, then OR makes sense. For example, for a movie rating cannot be both PG and R, so a logical OR makes sense--I would expect to see both if I selected both. But for a category like movie genres, or some other kind of tag, the items in that category may not be exclusive. If I selected Action and Comedy in the genre category, should I see all action films and all comedies (logical OR behavior), or films that are both action and comedy (logical AND behavior)?

**Comment by mcarrano** [comment]
@cshinn I think your logic makes sense. We did have some use cases for this within the storage console and I believe that's the logic we used. It would be interesting to test your design against our use cases to see if it will satisfy these requirements. @ncameronbritt I see your point about film genres, but it's hard to know what users would expect in this case. It we followed Chris' logic, the films that match both categories would be sorted to the top so the user would be presented with those first w/o loosing the others that match only one. This seems like a reasonable approach IMO.

**Comment by Mgranfie** [comment]
Question on how we document the filtering and results behavior. This has also come up with the Toggle Filter mechanism that @deernano Melody is working on. There are two ways to perceive how we document the filtering behavior:
1. How the end user perceives it, the sentence you make when selecting the criteria.
ie: I want to look for shoes in black, brown and tan. So to the end user it's an "AND"
2. The actual technical implementation of the query.
ie: The backend needs to find any shoes in black or brown or tan, to display for the user, so technically it's an OR query.

It was not until I realized which perspective we were documenting that the UI made sense to me. This might be worth noting, so that we understand and all make sure, as we move forward, we capture and document queries from the same perspective or note which perspective is being documented...

**Comment by mcarrano** [comment]
@serenamarie125 to coordinate with Chris to call a mtg for preliminary review.

**Comment by serenamarie125** [comment]
This is being tracked by https://patternfly.atlassian.net/browse/OSUX-109

**Comment by cshinn** [comment]
Initial documentation has been created and is available here https://docs.google.com/a/redhat.com/document/d/1Jjx0kNe6qb4lCK26w5wbDriRmObenw6CeTqwY5J4eqs/edit?usp=sharing

**Comment by mcarrano** [comment]
@cshinn So given your document, is the Faceted Filter solution what you are now calling the Checkbox Filter? If so, I'd advise renaming or closing this issue to avoid confusion.
