### ISSUE TITLE
pficon-remove and pficon-delete is redundant 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#360]
## For Bug contributions, please provide the following information... 
- [X ] I would like to report a bug<br>

pficon-remove and pficon-delete is redundant. do we want both?

**Comment by mcarrano** [comment]
Need visual team to create unique concepts for remove and test.  Need more research on usage. What products will this impact?  Do we also need to do the same for Create vs. Add? Next Steps:

1.@LHinson will send mailing to collect more data
2. Create new story for visual design backlog to generate concepts.

**Comment by mcarrano** [comment]
@LHinson @kybaker Thoughts about next steps on this? I am going to move back into backlog as I'm not aware of any activity. Let me know if there's someone who can pick this up.

**Comment by kybaker** [comment]
@mcarrano Sounds good.

**Comment by serenamarie125** [comment]
@mcarrano do we need a visual differentiation between the two?  I'd suggest that next steps would be research rather than having icons created.

**Comment by mcarrano** [comment]
+1 @serenamarie125 I think that's what we had previously agreed. In any case we need someone to pick this up.

**Comment by mcarrano** [comment]
@jennyhaines @schizari Given the icon work you both have been doing, wondered if you could give this a look. We currently do not have separate icons for Delete and Remove, although they are functionally different. Do you have any ideas on this?  Do you think users understand the difference?

**Comment by schizari** [comment]
@mcarrano based on our recent research results, most users associated the ‘trash’ with delete/deleted function both in context and out of context. There were 5 (out of 20) instances that users describe the icon as 'remove'. And from that 5, half of them mentioned 'delete' and 'remove' together. So there is a high chance that users tend to understand the icon as ‘delete’.

**Comment by jennyhaines** [comment]
@mcarrano @LHinson - I don't know of any difference function-wise between "delete" and "remove", so I don't see why we'd need to keep both. It makes sense to me to follow the results that Sara got, and only keep "pficon-delete" since that wording seemed to resonate more with testers/users.

**Comment by mcarrano** [comment]
There actually is a functional difference in many use cases, @jennyhaines .  Delete is destructive, remove is not. Removing an object in the context of management does not get rid of it. It's still there and I can potentially add it back later. Not sure that we often have Delete and Remove shown together, but I do think that the Trash icon is not the right metaphor if what I really want is to temporarily remove something.

Does that make sense?

**Comment by jennyhaines** [comment]
@mcarrano - That does make sense. In that case, keeping "pficon-delete" the same (as the trashcan) seems to make sense, and determining a different icon for "remove" could be good. I'd be curious to see a current UI that uses "remove", because it seems that the "close" icon (the X) could serve dual purposes... to close or remove.

**Comment by mcarrano** [comment]
We had Remove actions in Storage, but they were all from actions menus so this issue did not come up. @serenamarie125 @maryclarke @catrobson are you aware of specific examples of where we need a Remove icon?

Using "X" or something like it seems like a reasonable direction.

**Comment by mcarrano** [comment]
p.s. something like fa-minus-circle might also work. It feels more like the inverse of pficon-add-circle-o.

**Comment by catrobson** [comment]
@mcarrano yes, we do have "remove" as separate from "delete" as a concept in many places in our products, and I agree the trash can would be inappropriate for "remove".  I'm not sure that we use icons very often for this though, the only ones I can think of are text only buttons or kabob menu options.

**Comment by deernano** [comment]
@mcarrano I did a small research on what metaphor we should use for 'remove'. Hope it is helpful :)
https://docs.google.com/document/d/1duqO0gYgpvpL-SmxYuhcHhU3g2tsz2uF4yas8CEMIBw/edit?usp=sharing

**Comment by mcarrano** [comment]
@deernano Thanks for picking up this issue. I have reassigned it to you. I read your recommendations and think that using some variation that includes the "-" symbol makes sense. I would vote for 'fa-minus-circle' since we use 'fa-plus-circle' for Add. @kybaker and @jennyhaines can you look at Melody's recommendations and comment? @LHinson FYI.

**Comment by jennyhaines** [comment]
@deernano - I also think the "-" makes sense! @mcarrano - I thought that we are using the 'fa-plus-square' for Add (not the circle). That's what we have recommended in PatternFly now. I would recommend using the 'fa-minus-square' [https://fontawesome.com/v4.7.0/icon/minus-square/](https://fontawesome.com/v4.7.0/icon/minus-square/)

I noticed that the two icon suggestions in the Google doc are from the latest version of Font Awesome, though we are currently supporting the 4.7 version of Font Awesome. The 'fa-minus-square' icon is solid, rather than a line icon in the 4.7 version.

**Comment by jennyhaines** [comment]
For whichever icon we decide on, I can make sure that in the PR I'm creating for the updated PF icon table, I include our recommendation.

**Comment by deernano** [comment]
@jennyhaines @mcarrano 
great~ I agree with u by using 'fa-minus-square' 4.7.0. Just pasted it in ghe doc.

**Comment by mcarrano** [comment]
OK. If we are all in agreement here, I am going to reassign this to @jennyhaines to add this guidance to the icon table as she is making other updates. Thanks for your help @deernano . I don't think there are any further updates to make here.

**Comment by mcarrano** [comment]
@jennyhaines Have you addressed this with other icon table changes? If so, I will close this.

**Comment by jennyhaines** [comment]
@mcarrano  - yes I have! Feel free to close it out.

**Comment by mcarrano** [comment]
Thanks @jennyhaines I will close.
