### ISSUE TITLE
Horizontal Nav is outdated and inconsistent

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#387]
#### 1. Choose the type of contribution for this pattern:
- [ ] This is a new pattern 
- [x] This is an enhancement on an existing pattern

The existing responsive behavior of the Horizontal Nav pattern (see http://www.patternfly.org/pattern-library/navigation/horizontal-navigation/) differs from Vertical Navigation (http://www.patternfly.org/pattern-library/navigation/vertical-navigation/) These should be made consistent.

Vertical navigation is the most up to date design and should be used as the standard.  Specific issues with horizontal nav responsive behavior include 
* inconsistent placement of the hamburger menu.
* Missing placement and behavior of the notification drawer.

**Comment by mcarrano** [comment]
Created PatternFly story: https://patternfly.atlassian.net/browse/PTNFLY-2525 assigned to @deernano

**Comment by deernano** [comment]
@mcarrano 
Hi Matt, just updated the Horizontal Navigation Overview and Design part. Since theres a lot changes. I made a google doc version first for comments. Please help to review it. Thank you~
https://docs.google.com/document/d/1mpYKI53BG9vmGCnlQvenu7Ev5U6_6EqeFGfYIUJOa7A/edit#heading=h.5fpwsjtoqqhg
What I've changed:
1.Changed the position of the hamburger menu
2.Add responsive behavior
3.Add responsive behavior of horizontal navigation with notification drawer.
4. I found that theres some description of overview and design which are neither aligned with the code nor aligned with the vertical navigation. So I made some changes, please help to review this as well. ( The content I 've changed is marked as black. The content that I didn't change is marked as gray)

**Comment by mcarrano** [comment]
@deernano Thanks for summarizing this content in a Google doc and considering consistency between design and current code examples. I left some comments in the document. Here are a couple of general pieces of feedback to consider:

1. The treatment of the masthead in some of the mockups is outdated and no longer consistent with the latest masthead design. I believe that the code samples for horizontal nav have been updated, but the design mockups should be also. Is this something you can do as part of this process?

2. Your recommendations for responsive behavior of the menu make sense, however I note that these are different from the way we handle multi-level navigation for the responsive vertical nav (see http://www.patternfly.org/pattern-library/navigation/vertical-navigation/#/design) Specifically, when there is a second or third level of navigation, we use a drill down rather than a stacking approach. My assumption is that once we go down to mobile size, the horizontal and vertical navigation patterns should work exactly the same since at this point it is essentially the same mobile navigation. Does this make sense? @LHinson and @matthewcarleton I would be interested in your thoughts on this. Not sure what the implementation currently does.

I also saw that you made some updates to the text to match the code implementation around how hover states work for the two-level menu. This is probably a result of earlier conversations, but as I look at this now, not sure the design should change. @deernano was there a specific reference example you were looking at? Would like to explore this more.

**Comment by Mgranfie** [comment]
Great work Melody! it might be interesting to loop Cat into this convo.
Melodies solution is the same solution we looked at to address the deep
level navigation in .io and mobile, in .io, in a responsive manner, as the
pull right panels were not a mobile solution, without the back button.

-Monica

**Comment by matthewcarleton** [comment]
@mcarrano @deernano @LHinson I agree Matt, I think we should stick to one way of doing it. The drilldown method is a bit more graceful as it allows for more space and doesn't require scrolling as often. I also think visually the drilldown is easier to consume.

**Comment by deernano** [comment]
@mcarrano @Mgranfie @matthewcarleton 
I will change the design to the latest veision mirrors the vertical navigation first.
For the multi-level navigation state. I have a question. If we use drill down only, when the user wants to see the third level content of a multi-level navigation, they need to click twice and go back twice. And we recommended to use horizontal navigation when:
 "There are a small number of fixed categories. You want to provide the best visibility to primary categories by placing them immediately below the page header area. "
If the number of the categories are fixed, that means the first level will have fixed and not very much number of buttons. The second level could be some tabs or a dropdown list in desktop verison, which is more like a stacking approach.
That's the reason why I made the second level a stacking approach rather than a dirll down in order to save one going back step and also make it similar to the desktop verion of horizontal nav.
Any concerns about this ?

**Comment by mcarrano** [comment]
@deernano Sorry to not get back to you sooner.  We did talk about this yesterday and decided we will not change the implementation of this to match the vertical navigation as earlier stated. At this point the horizontal navigation is not frequently used and we don't want to invest in re-writing this code. So I think what that means is that the stacked approach that you specified is closer to what we want to document. Do you have a working version of this to look at? Please document the behavior of the secondary menus as it currently stands. The one exception is the placement of the hamburger and how the notification drawer is integrated. @matthewcarleton was going to look into this a bit more and give us a recommendation. Currently the notifications are not very visible when in the responsive state. Please ping me on Slack if you need further clarification.

**Comment by deernano** [comment]
@mcarrano ok I get it, Thank you ~

**Comment by mcarrano** [comment]
Verified. Will close.
