### ISSUE TITLE
Add guidance to the login page re: a failed login attempt

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#470]
This is an enhancement to an existing pattern ([login page](http://www.patternfly.org/pattern-library/application-framework/login-page/
)) to include additional documentation regarding a failed login attempt.

Currently our documentation states that we should show an informational or error message about the failure.

We should include documentation stating that both the user name and/or password are cleared along with posting an error message.

Note that although this may be an annoying for the user, it does satisfy security concerns.

Stakeholders @serenamarie125 @mcarrano 
@maryclarke @catrobson do you agree?

**Comment by catrobson** [comment]
agreed with this solution for more security

**Comment by yih-wang** [comment]
@serenamarie125 I'm just working on the guidelines of error message in login page. I can take this task and finish the document.

**Comment by mcarrano** [comment]
Thanks for taking this one @yih-wang . I have assigned you.

**Comment by mcarrano** [comment]
@yih-wang Do you consider that this has been addressed by your new login page designs?

**Comment by yih-wang** [comment]
@mcarrano I already added the guidance to the beginning of the Server-side Errors. It will be updated to PatternFly together with the login templates.

**Comment by yih-wang** [comment]
@serenamarie125 @catrobson @mcarrano When I'm writing the new Login Page Document. I'm thinking of maybe it's better to just clear the password field when an error message occurs. In most cases, errors come up because of typos. Keep the username will save time and effort for users. I think clearing password field is also safety. 
I stuck a comment in the guideline document. You can also find some related wireframes.
https://docs.google.com/a/redhat.com/document/d/1Ct6WqRhOzyBhqyT9ZNJ_bPdLUocMPDZDZlPVNqSFjoQ/edit?disco=AAAABh589UY

**Comment by mcarrano** [comment]
This suggestion by @yih-wang seems more in line with what I typically see. Does anyone see a problem with this approach?

**Comment by mcarrano** [comment]
This issue is addressed as part of #501

**Comment by mcarrano** [comment]
@serenamarie125 I believe this issue has been addressed as part of the documentation for new login page (http://www.patternfly.org/pattern-library/application-framework/login-page/). Please verify and close if you feel like this has been addressed.

**Comment by mcarrano** [comment]
I don't think we ever resolved details of what happens after a failed login attempt because of a mis-typed userid or password. Currently design specifies that only password field is cleared and a message "The account or password you entered is incorrect."   I think it is a good approach that balances usability and security. @serenamarie125 and @catrobson do you still have concerns with this?

**Comment by catrobson** [comment]
@mcarrano yes, this works for me.  I know the team had created a bunch of variants, but from a PatternFly recommended solution I agree this is what we talked about as a good balance of usability and security.

**Comment by serenamarie125** [comment]
I'd like to put up a quick PR with some higher level info to help set the context.  I'll put something up by the end of the week!
