### ISSUE TITLE
Add Actions pattern for guidance on Toolbar actions

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#508]
This is an enhancement to the Kebab Menu documentation.

To aide with learnability, a "More Actions" tooltip should be available on the Kebab Menu.

**Comment by mcarrano** [comment]
Let's consider this part of a new pattern that concerns "Actions" whether they occur in a toolbar, listview, or other.

**Comment by mcarrano** [comment]
Should consider whether tooltip should be a standard element of the menu component or is this a new design pattern that specifies use of actions?

**Comment by mcarrano** [comment]
@cshinn had done some earlier work on Actions that was never published to the PatternFly website. See https://docs.google.com/document/d/1zDF8JoT9oDBr__KGS4uBE5X9VkMfxlFG5tPqSc1P6UU/edit?usp=sharing

I think that this provides a good starting point for documenting Actions as a new pattern and would be the right place to address the tooltip issue. This pattern could be generalized to make it clear that the Actions bar can exist within a toolbar, a list entry, or a card with corresponding examples.

@serenamarie125 @catrobson @maryclarke @jeperry thoughts?

**Comment by jeperry** [comment]
Agree this is the right place. i think this is a very obvious thing to have a high level pattern for and would be much appreciated.

**Comment by serenamarie125** [comment]
+1.  @mcarrano can we all review Chris' doc, and then I'll create a OSUX story for him to formally contribute Actions to PF?

**Comment by mcarrano** [comment]
Yes, let's do that. If you haven't already done so, please take a few minutes to review the Google doc (it's short!) and feel free to comment. We can move forward from there.

**Comment by mcarrano** [comment]
@catrobson @maryclarke can you review Chris' doc (see above) and let us know if you are good to proceed with adding Actions as a new pattern?

**Comment by cshinn** [comment]
@mcarrano I'm working on bringing that doc in line with more current patterns (its about three years old at this point) but I should have a PR up in the next couple days to check out

**Comment by cshinn** [comment]
I've run across an interesting challenge with respect to the tooltip. Because the more actions kebab is often close to the edge of the screen, any tooltip above it will get cut off. ![screen shot 2018-01-15 at 4 07 42 pm](https://user-images.githubusercontent.com/3300756/34961747-9cb2111c-fa0e-11e7-846e-c5eaf30227b7.png)


A tooltip to the side will have to overlap other parts of the toolbar, which doesn't look very good. 
![screen shot 2018-01-15 at 4 08 14 pm](https://user-images.githubusercontent.com/3300756/34961748-9ddf6760-fa0e-11e7-9c8b-8ec2d1088553.png)

Thoughts?



I know that we could have the caret off to one side, but I believe that would require a special implementation just for this

**Comment by mcarrano** [comment]
Hmmm... So are you saying that our tooltips won't adjust when they intersect with the window boundary?  @andresgalante thoughts about this?

**Comment by cshinn** [comment]
@mcarrano they can adjust, but as far as I know, you'd end up with something like the second image. Which seems sub-optimal

**Comment by mcarrano** [comment]
@cshinn can you please address #593 and #594 as part of this work?
