### ISSUE TITLE
Clarify use of alternate login methods in Multi-Factor Login

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#548]
The [Multi-Factor Login](http://www.patternfly.org/pattern-library/application-framework/multi-factor-login/) documentation lacks clarity around use of "Other Login Methods." There are two primary issues that I see:

(1) It's not clear where these screens fit into the overall flow. After the system validates the username, do these screens come next (i.e. before the password), after the password screen, or in place of the password. It might be helpful to include a flow chart or similar diagram that shows this sequence.

(2) It's unclear why the Other Login Method screens have a user icon in front of the username but the password screen does not. What's the difference? Also, is this intended to just be a static icon or an avatar? If the later, I think it should be marked optional since all underlying systems may not support that. If we intend to keep this, should add a callout to describe what it is.

**Comment by yih-wang** [comment]
@mcarrano I made some updates and pulled a request #549 to fix these two issue:

1. For Overview page, changed the subtitle "Other Login Methods" to "Additional Authentication Methods", and modified the description to better demonstrate the relationship between these screens. 

I also moved the one-sentence description of Authenticator/SMS/Backup Codes from Design page to this part. Because it's more like a summary and doesn't involve detailed designs.

2. For Design page, added avatar to the password screen and marked this feature as optional. Also put a multi-factor login example behind to show how these screens fit into the overall flow.
