### ISSUE TITLE
Unclear guidance on color usage (red)

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design#558]
I would like to report a bug on design documentation.

Guidance on color usage is inconsistent.
pf-red is #a30000. The status palate uses pf-red-100 #cc0000 (red hat red) and pf-red-300 #8b0000. The error alert and pficon-error-circle-o both use #cc0000. 

When should pf-red or pf-red-300 be used? 

A Red Hat specific issue that has come up is Brand would prefer if we do not use our brand color to designate bad / destructive / error UI elements. Should we consider removing pf-red-100 from the status palette and instead using pf-red? Possibly universally or having specific RCUE guidance for colors?

**Comment by mcarrano** [comment]
@kybaker can you take a look at this and comment?

**Comment by kybaker** [comment]
@ajacobs21e This is a great point. We should always use pf-red this will avoid any conflict with brand guidelines. I added pf-red-300 to the status palette as an accent if we needed it for things like outlines etc. 

@mcarrano Can we make a story to go through the PatternFly library and website to update the alert/error color from pf-red-100 to pf-red? I am not sure if there is a single status or alert red we are using or if we will need to go through each component. I don't think we need to update any of the website pattern imagery because I think the resources required would outweigh the benefit.

**Comment by ajacobs21e** [comment]
thanks @kybaker 

@mcarrano let me know if I can help at all

**Comment by mcarrano** [comment]
Per 2/26 UXS Call... @kybaker will file new issue against patternfly core and reference this issue. Not changes to design needed at this time.

**Comment by mcarrano** [comment]
I have created a PF core issue t track this. See the above reference.
