### ISSUE TITLE
Bulk Editing of a table

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-design#564]
- Unsure if this is a new pattern or an enhancement to a table

We have 3 instances in different products utilizing bulk editing of a table.  Essentially, allowing a table to be put in edit mode, then all cells become editable.  And then the user can save the edits.

Here's an example of OpenShift's implementation:
<img width="1331" alt="screen shot 2018-02-12 at 1 49 47 pm" src="https://user-images.githubusercontent.com/12504403/36113789-0273f42c-0ffc-11e8-99d0-7154dd309c86.png">
<img width="1334" alt="screen shot 2018-02-12 at 1 50 04 pm" src="https://user-images.githubusercontent.com/12504403/36113788-026057aa-0ffc-11e8-8e18-b18e5bbe185b.png">

**Comment by serenamarie125** [comment]
@mcarrano this is an example of a use case that is being supported differently by CloudForms, OpenShift & Satellite.

**Comment by mcarrano** [comment]
I am going to start by calling this a new pattern. We do have [Inline Editing](http://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/) but I agree this is a different use case. We should also consider whether this might apply to list views as well as tables.

**Comment by mcarrano** [comment]
@Mgranfie Is this something to consider as part of your table investigation?

**Comment by serenamarie125** [comment]
@Rohoover once you have a proposal for Satellite worked up, can you add the mocks here so we can use it as input for a pattern?

**Comment by Rohoover** [comment]
@serenamarie125 Yup. Here it is!

[Table Bulk Edit.pdf](https://github.com/patternfly/patternfly-design/files/1760174/Table.Bulk.Edit.pdf)

**Comment by Mgranfie** [comment]
@mcarrano Yes, this should be included in the table evaluation. Thanks for noting and please keep me in the loop here.
@Rohoover this is great! I have a few questions on the intent and the behavior.
1. Is the intent to put all the fields in one column into an edit mode and be able to tab or arrow between them and enter new data? I was not sure because the 3rd image shows two fields displaying the pencil and one has a hover state and one does not.
2. Does this UI allow for bulk edit meaning if I want to change all the values in the column to a single value, I can or is this not one of the use cases?
3. If I click to edit on field it looks like you go into editing mode for all the fields on that column?
4. What would the behaviors be in the individual field, like escape to undo an entry or is it all or nothing?

I may have missed some pertinent discussions here, so I may be asking questions that have already been answered. Just a few gaps in my understanding.

**Comment by Rohoover** [comment]
@Mgranfie 
1. In this instance, only the fields in that column are editable. Theoretically any and all editable fields would be editable. The pencil is the icon we use on hover (already defined by patternfly), and it's currently used again to indicate the field was edited. There are other good pencil icons but I don't have access to them since font awesome changed their site and permission levels.

2. This is currently not one of the use cases. In our use case it is highly unlikely you would change all fields to be the same.

3. Yes, the entire table becomes editable. There is a technical reason why inline edit of a single row was not feasible, so all fields become editable.

4. "X" would cancel out any changes made to the table. Currently there were no plans for esc to reset the field. I'm not against it, just in this case it wasn't in scope.

**Comment by Mgranfie** [comment]
@Rohoover  thanks just a couple of follow ups
1. It sounds like when in edit mode, all fields in that column are editable?
2. I like the idea of having the pencil to indicated edited! It was a little confusing but now makes sense. Maybe an outline pencil and then fill on hover?... not a big deal.
3. My expectation on clicking on a pencil, on hover, for a single field, would be that it would move only that field into edit mode. And so for this UI the only editing is on the table level, no individual level editing. This was not clear to me. It was not visually apparent to me that the entire table was now editable and thought that it was just the field or at most the column that was in edit mode. I think because in the last column the cells now appear as fields, but the other columns do not. Is there interaction that moves into this mode when you click on another column, or is there a more global method with which to put the table into an edit mode? I am wondering if this is the type of interaction that becomes more apparent with use and I am missing the cues with static images...
4. Got it, makes sense, given the granularity of the field level changes, that cancelling the field level changes is out of scope : )

**Comment by Rohoover** [comment]
1. Yes. In my case, only that column is editable (because that is all you could edit) but I could see a use case where any and all editable fields in the entire table are editable.
2. Yea, I saw a hollow pencil but don't have access to that icon. I opted to use the same icon vs. pull a new icon that was stylistically dissimilar. 
3. The click can occur anywhere in the field as referenced in the exiting PF pattern.  I looked at global button for putting the table in edit mode but in my particular product there is button overload and there wasn't an ideal placement for it. We also thought that supplying a button would be counter to the already existing inline edit functionality in PF.

**Comment by Mgranfie** [comment]
Thanks @Rohoover ! To sum this up, the Bulk edit, invoked an edit mode on a singular column, in which only individual fields can be edited? Am I getting warmer :)

**Comment by Rohoover** [comment]
For my use case. However, if another column was editable, those fields would become editable as well.

**Comment by Mgranfie** [comment]
Thanks got it!

**Comment by mcarrano** [comment]
Per 3/2 PF-UXS meeting: This still requires requirements gathering and concept design work. Will mark as "Help Wanted" and move to the backlog. Satellite design attached from @Rohoover should be considered a point of departure but not the comprehensive solution.
