### ISSUE TITLE
Social Login Pattern 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-design#585]
All of the Login implementations have their own patterns however social login is missing. 

On PF.org: 
- Basic: http://www.patternfly.org/pattern-library/application-framework/login-page/
- Multi-factor: http://www.patternfly.org/pattern-library/application-framework/multi-factor-login/
- SSO: http://www.patternfly.org/pattern-library/application-framework/single-sign-on/

Missing:
- Social login https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/login-social-account.html

**Comment by mcarrano** [comment]
@LHinson When we discussed organization of the new login pages, we made a decision to just include the social login as a variation of the standard login page rather than call this a separate pattern. From a test page point of view, not sure if standard and social login should be combined onto one test page, kept separate, or if it matters.

Thoughts?
