### ISSUE TITLE
Progressive disclosure lacks code example & formal widget

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly-design#706]
I noticed there is no HTML or React code example for progressive disclosures, even though a design exists.

I've written a bit of code with the goal of using just HTML+CSS (no JavaScript needed). Unfortunately, this means we cannot nest the `<input>` in a `<label>`; we have to rely on the `for` attribute. Aside from that, everything "just works".

Class names and HTML structure may change, but I think this should work as a good first start:

https://codepen.io/garrett/pen/qyGjvM

**Comment by garrett** [comment]
Just FYI: I'll be on vacation for 2 weeks, but I might sneak a peek at GitHub. (No guarantees though. :wink:)

**Comment by seanforyou23** [comment]
I love the concept, and the implementation looks good, too! I had some thoughts, the main ones were

1) You may want to consider adding classes to each of your html elements that you target for styling, so that the selectors don't rely as much on specific DOM structures being present. For example instead of `.disclosure input` you could use `.disclosure .pf-c-form-control` or something like that. Doing this across the component suite will allow the html and css devs to more freely refactor the underlying markup structures without requiring as many changes to the JavaScript APIs and "contracts" we'll be putting into place on the framework side to support this.

2) On the topic of contracts, the use of `~` general sibling selector is required for this to work, as is a specific structure of accompanying markup. It would be good to see that this works in a JS implementation. If this pattern ends up being difficult or impractical to produce in a framework scenario we may just want to consider that when we go to write documentation around the example.

**Comment by mcarrano** [comment]
@garrett @seanforyou23 Since this issue proposed code to be added to the PatternFly core repo, I have created a new issue there and will close this one out. See https://github.com/patternfly/patternfly/issues/1130. Please move this discussion there.

@garrett If you want to continue to work on this, we would love to have you contribute it. Please feel free to assign the issue to yourself. Let me know if you have any questions.
