### ISSUE TITLE
Introduce content guidelines

### ISSUE THREAD

**Issue by stacymcauliffe** [patternfly/patternfly-design#722]
Introduce guidelines around writing for products 
Include information on:
- [x] Embedded assistance
- [x] Writing for UX
- [x] Terminology, grammar, and mechanics

**Comment by stacymcauliffe** [comment]
Submitted draft for review: https://docs.google.com/document/d/13xRWU3OFmzcq0VU4R_38jIRSBdMKFksU51Dt1Fa3MEo/edit?usp=sharing

**Comment by stacymcauliffe** [comment]
Updated draft docs: https://docs.google.com/document/d/1E1sRqp64AiqTLTXm569bGNpEtZHm-oYpTCl3jOBAWcE/edit?usp=sharing

@mcarrano

**Comment by rachael-phillips** [comment]
I'm following up on this issue. Any updates here?

**Comment by stacymcauliffe** [comment]
Content guidelines have been merged but are not yet showing up on the site. Not sure how to fix that - @jschuler or @mcarrano - any ideas?

**Comment by mcarrano** [comment]
@stacymcauliffe I'm just guessing, but it may be that you need to structure this content the way we structured other design guideline docs. So that means each topic needs its own folder that is named how you want it to show in the Nav. Inside that folder you should have a design.md file for the content and a /img folder with images.

@jschuler can you confirm this? I'm guessing that this is what you are scanning for to build pull in these pages.

**Comment by stacymcauliffe** [comment]
Now building in the UI. Closing
