### ISSUE TITLE
Improve Select All function for bulk selector

### ISSUE THREAD

**Issue by yih-wang** [patternfly/patternfly-design#731]
- Enhancement on an existing pattern 
- This is designed for potential request in EnMasse.
- In the current design for bulk selector, users can click "Select All" checkbox to select all the items in the current page. However, if they want to select all items from all pages, they need to click "Select all" page by page. We should provide a one-click button for this function. In addition, it looks the same when all items in current page are selected, or items in all pages are all selected. That's because we don't clarify how many items are totally selected.
- Depending on the bulk selector: https://www.patternfly.org/pattern-library/forms-and-controls/bulk-selector/
- I have created some solutions which can be found here: https://redhat.invisionapp.com/share/7TOTLHR36PA  
- @patternfly/patternfly-design-maintainers

**Comment by mcarrano** [comment]
I just reviewed and commented on your InVision prototype @aprilma419 . Overall the approach looks good. My only question is about the wording of the message. See my comment.

**Comment by aprilma419** [comment]
Hi Matt, I re-considered what you have mentioned in the comment. "filtered items" only represents the filtered lists, which is not a perfect wording here that may also confuse users. 

So I just fixed them as you said in my designs. Please check it out when you have time, thanks!
https://redhat.invisionapp.com/share/Q7P86OV2KRX#/333236438_bs_2


@mcarrano

**Comment by mcarrano** [comment]
@aprilma419 This is definitely better. As I reviewed this again, there were just a couple of additional comments. @stacymcauliffe can you take a look at the wording in the mockup? I wasn't sure whether "Select all 25 items across pages" or "Select 25 items across all pages" was more correct grammatically.

I will also send this out for review by the UX Leads and if there are no major changes, I think we can proceed with updating the patterns via a PR. Thanks @aprilma419 !

**Comment by aprilma419** [comment]
@mcarrano Okay, I've already updated the designs on InVision. Let me know if there are other questions. Thanks!

**Comment by mcarrano** [comment]
This looks good @aprilma419 . I reviewed today with the UX Leads and they gave the go ahead to submit this as a PR. There was only one question that came up during the review that you should think about. What happens if you have all items selected and the user unchecks one or more items? I tried this in Gmail and the bulk selector goes to a mixed (-) state and the toolbar returns to it's normal state. If you agree with that approach, please be sure to document it. Our situation is a bit complicated by the fact that the default PatternFly checkbox does not support a mixed state. So the question is what do we do then?

To update the pattern with this variation, you should be updating the existing Bulk Selector pattern doc on GitHub here: https://github.com/patternfly/patternfly-design/tree/master/pattern-library/forms-and-controls/bulk-selector  Let me know if you have questions.

**Comment by aprilma419** [comment]
The PR #735 has been merged, so closed this issue. If anything needs to update, I will reopen it.
