### ISSUE TITLE
Progressive Form

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-design#750]
Request from the OpenShift team for a progressive form.

**Comment by mcarrano** [comment]
A usability study was completed to compare performance and user preference for a progressive form vs a wizard in a simple object creation use case. A report on this study can be found here: https://docs.google.com/presentation/d/1pU5XdhtzHCA8hgIPY74egypj8dUJ8_M10_25zOqMKww/edit?usp=sharing  and prototype for testing here: https://preview.uxpin.com/cc889a55d206dbb2a21f4c01351624e9c513f212 The prototype presented a step-wise task as a single scrollable form without including Next and Back buttons. The user could use the keyboard as well as the mouse to scroll through the form. Completion was via a submit button at the bottom of the form. A stepper located in the left-hand margin allowed the user to jump around within the form by scrolling to a pre-defined anchor upon click.

Some high-level take aways:

- The progressive form performed marginally better than the wizard and was the preferred approach for most users. Participants liked the ability to have all settings presented on a single scrollable page rather than broken into smaller chunks. There was some concern that this advantage might break down for very large tasks (more than 10 steps), however.

- Numbered and labeled steps were important as well as providing a clear sense of where the user currently is in the process (e.g. percent done).

Recommended next steps:

- Further refine the design of the stepper navigation leveraging some of the earlier work done here. It would be desirable to reuse the same stepper between the progressive form and wizard.
- Build a Progressive Form demo that mimics the prototype used for testing. Other than introducing the stepper, it should be possible to build this from existing components.

Need to assess roadmap priorities for this.

cc @rachael-phillips @LHinson

**Comment by andrew-ronaldson** [comment]
@mcarrano Here is a [link](https://marvelapp.com/prototype/1774e319/screens) to the latest mockups using jump links instead of the Wizard styling. I'll record a separate demo and share soon.

**Comment by andrew-ronaldson** [comment]
Here's the quick demo video.  https://images.zenhubusercontent.com/61041252/3501db97-077e-449e-a780-3631c49ddd59/screen_recording_2022_04_22_at_4_38_17_pm.mov

**Comment by andrew-ronaldson** [comment]
Here's the demo recording.
https://user-images.githubusercontent.com/28658548/164783252-a75d2163-aa21-4546-a5d0-98b094a2bc54.mov

**Comment by mcarrano** [comment]
Thanks @andrew-ronaldson . I have opened https://github.com/patternfly/patternfly/issues/4805 to move this along and create a demo that shows how to make this. @mmenestr we will probably need a design doc issue also for follow up.
