### ISSUE TITLE
Refining use of Secondary button and link button

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-design#755]
After speaking with @mceledonia, I've filed this issue with the goal for us to refine our component definitions around secondary buttons and link buttons. In thinking about PatternFly, the design team has moved towards more frequently using link buttons for secondary buttons. Further discussion will determine the impact beyond updating our design guidelines. cc @kybaker

**Comment by gdoyle1** [comment]
I looked at some other design systems and most of them were using the button styling that Michael supplied above with the gray bg for secondary buttons (thanks Michael). I've documented all states in this marvel project: https://marvelapp.com/54d49i2. I also put the secondary redesign within the rest of the buttons so we can see how it fits in.

IMO link buttons should remain the same and link text will also be a separate thing, which would remain the same as well.

Let me know what you think! @mcarrano @mceledonia

**Comment by mcarrano** [comment]
@gdoyle1 So if we do this, is the only difference between a Secondary button and a link button what the hover states look like? Do we really need both then?  In @mceledonia 's original mocks, Secondary button had a very light border in the default state. Did we intentionally omit that?

**Comment by gdoyle1** [comment]
@mcarrano woops I forgot to add the border! It's in there now

**Comment by mcarrano** [comment]
OK. Makes much better sense @gdoyle1 ! @mceledonia if you are good with this then I think we can pass to Dev for implementation.

**Comment by gdoyle1** [comment]
This design meets accessibility standards:
“The other myth you might hear is that a gray button is inaccessible because it doesn’t meet the contrast ratio standard. It turns out the success criteria for buttons doesn’t require a visual boundary indicating the hit area. If a button with text has a border, there is no contrast requirement beyond the text contrast (source). Therefore, the gray button that most would assume is inaccessible passes the contrast requirement.”
[source](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html)
[article](https://uxmovement.com/buttons/the-myths-of-color-contrast-accessibility/)

@mceledonia @kybaker @mcarrano

**Comment by mcarrano** [comment]
Following conversation today between @gdoyle1 @kybaker @mceledonia and I, we have decided to put these changes on hold and not make changes to existing button styling. If anything, we made look at enhancing design documentation to better guide designers on appropriate usage. 

Given that discussion I am going to close this issue and propose we close and remove the corresponding core issue from the roadmap. https://github.com/patternfly/patternfly/issues/2658 Thanks @gdoyle1 for all your efforts on this!

@mcoker @LHinson @rachael-phillips FYI
