### ISSUE TITLE
Tables embedded in white background needed

### ISSUE THREAD

**Issue by yih-wang** [patternfly/patternfly-design#778]
We need tables in the expansion of data list in AMQ. In current PF4 templates, all the tables I found occupy whole rows, and don't have clear borders. 

I created an initial wireframe for the requested table- 
<img width="1203" alt="Screen Shot 2019-05-17 at 15 58 37" src="https://user-images.githubusercontent.com/23331885/57912357-aa6d8600-78bc-11e9-9d7d-014e87c8c293.png">

**Comment by mcarrano** [comment]
@yih-wang @junezhang I revisited this issue with @mceledonia and we agreed that the best way to approach this will be to place the table in a card that has a single pixel border rather than introducing a border to the table itself. While we currently do not have that Card variant, we have an open issue here where we will be addressing the need for alternatives to the drop shadow across the library.

In the interest of issue maintenance, I will close this but feel free to add further comments to https://github.com/patternfly/patternfly-design/issues/800
