### ISSUE TITLE
Explore multi-level dropdown/select menu

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#790]
This is a request from Openshift as needed for topology view. For reference, the initial request was made in the React repo here: https://github.com/patternfly/patternfly-react/issues/3458

**Comment by mcarrano** [comment]
Design proposal has been attached to the core issue here: https://github.com/patternfly/patternfly-react/issues/3458#issuecomment-573820770

**Comment by mcarrano** [comment]
Thanks for addressing this @mceledonia . I will close this out.

**Comment by mcarrano** [comment]
Reopening this issue as responsive behavior requires further exploration. There is a proposal to do a tree style drill down, but this leads to development complications,

https://patternfly.slack.com/files/U8SGWKL15/FTNP72RS9/screen_shot_2020-02-06_at_2.55.26_pm.png

Should consider how this component may be used in context and what is an appropriate mobile behavior. See discussion in https://github.com/patternfly/patternfly-next/pull/2666

**Comment by doruskova** [comment]
@mceledonia @mcarrano 
I've been working on a responsive version for this multi-level menu. The link is [here](https://marvelapp.com/dhj94fe)

It seems that we have two options on how to deal with the responsive version for a multi-level menu. 

- [Drilldown menu](https://marvelapp.com/dhj94fe/screen/66701095)

- [Accordion menu](https://marvelapp.com/dhj94fe/screen/66779338) 

I've already reached Karthik for more information about Topology, because, in my opinion, it depends on how many levels/submenus this component can have. Both options have some advantages and disadvantages. More likable is a drill-down menu because it has a clear organization, but it can be frustrating for a user if you have e.g. five or more submenus. However, this problem can be solved with breadcrumbs.
The second option is the accordion menu. You have a high overview of what's in there, but sometimes it's difficult to navigate and when it has a lot of items >> lot of scrolling. 

So, the main question here is how big the tree can be and then it should be easier to agree on the solution. 

@mcoker What type of development complications the tree style drill down menu can have?

**Comment by mcarrano** [comment]
@doruskova Thanks for posting this. I agree with your analysis that the drill-down menu is probably the better choice. Besides the issues that you mention, it can support an infinite number of drill-down menus while it seems like the accordion would be restricted to one level deep. That said, I don't think it would be good practice to go more than two levels, although it would be nice if the component did not restrict that.

One question I have is whether we need to support the fly-out menu at all. Can we just have a consistent approach that works for either desktop or mobile applications? Interested to hear what others think.

**Comment by doruskova** [comment]
@mcarrano Sorry for the delayed answer. I got some info from Karthik and the current requirement is to support 1 level of the submenu. However, it's better to have 2 levels of nesting. 

I added a visualization of our current use case:  [Topology view](https://marvelapp.com/dhj94fe/screen/66867014)

**Accordion menu** can be used for both desktop and mobile versions, but it takes more space (increases when item extends) and it's not a good option for an infinite number of submenus. 

I still think that the most expected behavior for a desktop is the fly-out menu. My only concern is the hover action because you can easily lose a focus and the menu will close. So, IMHO it should be on a click cause you can move your mouse however you want. 

Drill down for a desktop is not suitable for our use case. It's good for site navigation, but not for this case. We would hide the content on a desktop unnecessarily.  

So, my suggestion is to use fly-out for a desktop and drill down for mobile but would be nice to hear what UI developer and other thinks. :)

**Comment by mcarrano** [comment]
@doruskova Thanks for sharing the visualization of the Topology view here. It gives me a much better understanding of what the problem is. I'm going to set up some time to discuss with you and @mceledonia as I'm wondering if a drop-down is really what's needed.

**Comment by doruskova** [comment]
@mcarrano yeah, thanks for a scheduled meeting.
I got some additional info from Karthik: 
- Topology isn't responsive. They support just hover actions that are not on touch devices.  
- They focus more on the larger screen.
- The menu appears when you right-click on the group.

**Comment by mcarrano** [comment]
Per discussion today with @doruskova and @mceledonia I am closing this out in favor of https://github.com/patternfly/patternfly-design/issues/774 which seems to better address the user need. We will continue design work in the context of that issue.
