### ISSUE TITLE
Request: Navigation collapses to maximize screen space

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-design#795]
It should be possible to collapse the vertical navigation in order to maximize the working content area of the page as left navigation consumes a significant portion of the horizontal page width, especially on smaller screens.

This would be an extension of the vertical navigation, where instead of collapsing into a hamburger menu, it collapses to a minimized form factor. 

This was available in PF3 via collapsing to an icon bar and was used extensively in Satellite. It provides the ability to quickly switch between pages while still maximizing content space. The lack of this feature makes a PF4 upgrade more difficult.

cc @Rohoover

**Comment by mcarrano** [comment]
@katierik @LHinson updated description based on Jan 9 meeting.

**Comment by mceledonia** [comment]
![Collapsed Nav Concept Gif](https://user-images.githubusercontent.com/30935938/73481186-4a930e80-4369-11ea-836d-86907b408b4e.gif)

**Comment by andybraren** [comment]
@mceledonia Man, that is really slick! 😄

A few interaction/implementation considerations that come to mind off the bat (recognizing that the GIF is a concept, and this is all super early stages):

1. Assuming that icons are shown when collapsed, we may want to recommend in our documentation that the same icons be used next to labels when the nav is expanded as well to support easier recognition of what's what.
2. The condensed navigation should probably support both top-level links (like the GIF shows) and top-level dropdowns that contain multiple links within them.
3. Ideally, the presence of section headings that separate groups of links should also be visually indicated somehow and fully visible when any item within that section is hovered/expanded.
4. For muscle memory reasons, the collapsed nav's items should likely be located at the same y-axis coordinates as the expanded version.
5. The icons themselves probably need to be hovered/clicked to reveal the titles or sub-links within the item, rather than the region to the right of the nav like the GIF shows, to not interfere with the clickability of anything in the content region.

**Comment by andybraren** [comment]
I commented before watching the the visual design meeting recording, oops! Glad to see everything above is already being considered. 🙂

**Comment by mcarrano** [comment]
Usability test results here: https://docs.google.com/presentation/d/15qomOHITAJhghWWrddGn-SpRgsaHhEzIxp0Pvh9MaGY/edit#slide=id.g7eef56b5e8_0_64

Findings are that while participants appreciated the ability to hide the nav and get more screen area, they did not find the "dots" to indicate current structure very useful. We should continue to explore alternate approaches.

**Comment by mcarrano** [comment]
Met with @katierik to review usability test results and brainstorm. Agreed that there is still a need for this pattern and it would be good to explore further concepts that don't require icons. Perhaps hiding existing vertical nav in an overlay drawer that is accessible on click or hover? See https://console.cloud.google.com for some ideas of how this could work.

Next steps - iterate on concept prototype and retest.

cc @LHinson

**Comment by mcarrano** [comment]
Any objection to closing this? It has been idle for over 6 months. Can reopen if this becomes a critical need once more.
