### ISSUE TITLE
Navigation problems with Tertiary nav widget on mobile

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-design#840]
We're trying to use the tertiary widget in our project (Cockpit), and we're having some navigation issues, especially on mobile.
It's very hard to get a good overview of all the items, the arrows have very small hit targets, that if I hit them gives a somewhat unsatisfactory behavior (so sorry for the vagueness, but I have a hard time putting my finger on what it is. I think it's something that it reveals the items little by little, but not sure).

I want to create a property where it does not do overflow: hidden; and just show all items inline after each other.
Any good pointers for how I can create that?

**Comment by mcoker** [comment]
@mcarrano transferred the issue.

**Comment by mcarrano** [comment]
@garrett @andreasn This issue is quite old and I wanted to loop back around with it. We have been working on redesigning the visuals for our tertiary nav component to differentiate it better from Tabs. You can see those designs here: https://marvelapp.com/prototype/fj0941h/screen/76571549 In looking back at this, it seems like you were using tertiary nav where you should have been using tabs (this is part of the reason we want to make these look more visually distinct). You can see the Tabs comonent here: https://www.patternfly.org/v4/components/tabs

That said, I wanted to investigate whether we still have an issue to solve. It may be that the same problems apply using tabs, in which case I think we can open a new issue to revisit the options.

**Comment by mcarrano** [comment]
I am going to close for now and perhaps we can revisit once we introduce other changes to the tertiary nav styling.

**Comment by garrett** [comment]
Just an update from the Cockpit side:

The main location where we used tertiary navigation as tabs was in the virtual machines page. Instead of using tabs, we are using a subpage where everything is in sections now.

However, we do have an open PR that is using tabs and it's hitting an overflow issue in mobile, much like mentioned in this issue.

It goes from this:

![Screenshot_2021-04-21 Netzwerk - garrett Rain(2) - mod](https://user-images.githubusercontent.com/10246/115538934-af06fa00-a29c-11eb-9dc3-2db180578bb4.png)

to this:

![Screenshot_2021-04-21 Netzwerk - garrett Rain(3) -  mod](https://user-images.githubusercontent.com/10246/115538947-b3331780-a29c-11eb-854a-1ff161745c2f.png)

(The screenshots are crops to the important part, as the rest is highly in flux. The UI is in German, in case you're wondering.)

There aren't many items to choose from, but obscuring the items with the overflow like this makes someone fight with the UI to get to the content (and even simply see what's available), instead of just tapping.

**Comment by mcarrano** [comment]
@garrett Thanks for the additional feedback. I have opened a new/fresh issue to explore this in the context of Tabs here: https://github.com/patternfly/patternfly-design/issues/1034 I'm open to reconsidering our current approach to scrolling the tabs, but this may be difficult to achieve without introducing a breaking change to the existing component.
