### ISSUE TITLE
Drill-down tree menu

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#867]
Need a drill-down tree menu that allows the user to navigate a hierarchical tree of items for selection or actions. See related discussion in #829.

**Comment by doruskova** [comment]
@mcarrano I'm adding a mocks to the multilevel drill-down menu -[ link here](https://marvelapp.com/66b0059). It's still in progress, but it should be finished the next week.

**Comment by doruskova** [comment]
@mcarrano Mocks for a drill-down menu have been updated. [Link here](https://marvelapp.com/66b0059). 
Does this approach work for you all @nlcwong @aprilma419 @ajacobs21e @yih-wang  
I think that the menu with breadcrumbs needs to be tested on someone because I don't know if it's not confusing for the users. I appreciate your thoughts and comments.

**Comment by nlcwong** [comment]
@doruskova The drill down looks great.  Yes, we'll definitely need to test the breadcrumb because the name of the step would more than likely be long and perhaps repetitive. Have we thought what it might look like truncated (the bookends of the breadcrumb that is)?

**Comment by ajacobs21e** [comment]
@doruskova The drill down menu doesn't meet my req of needing to go back to the top in one click. The breadcrumb version could work. If you do testing please let me know, I can provide my examples for testing and probably can help recruit (if not help with the actual test).

**Comment by aprilma419** [comment]
@doruskova These look great! I like how you did the approach of breadcrumb navigations, the only concern of mine is I'm not sure about the breadcrumb dropdown, what happens if the level list is very long(like 10 levels)? Will the dropdown menu be in a fixed height? Thanks.

**Comment by doruskova** [comment]
@nlcwong @ajacobs21e @aprilma419 Sorry for my delayed answer. Thank you for your comments. I've added a screen with a truncated name [here](https://marvelapp.com/prototype/66b0059/screen/70988488) and how the breadcrumbs behave when you go more levels deep [here](https://marvelapp.com/prototype/66b0059/screen/70992097). 
I agree that the breadcrumb dropdown can't include, for example, 20 items. I think that 5 items are maximum IMHO, then it gets messy. I created a way of how to show a little more items [here](https://marvelapp.com/prototype/66b0059/screen/70992097). But, if you need to include more than 10 levels, I think that the only way is to group categories and show just "All apps", "All something". And maybe it's for a different discussion about data structure with an architect. 
@mcarrano What do you think? I'm also thinking about selecting items from the drill-down menu because the user needs to see what's been added somewhere. In Alli's use-case, there's a need to select items/filters from the drill-down menu. And these selected items work as a filter, so they are added as chips. However, I think that it works because you can see that something is happening right away. But, the problem may be, when you select items and then you have to take action above them. The user can easily forget what's been selected. For these cases, I would use a tab box above the drill-down menu that says "Selected items". But, it's for a deeper discussion and it's more complicated.

**Comment by mcarrano** [comment]
This is a tough question @doruskova . I agree that it gets messy if you drill down more than 5 levels, but maybe that's an information architecture problem and not our problem to solve from PatternFly. So I think that just expanding the breadcrumb to a flat list of parent nodes is good enough and we don't worry about how long that list can be. What do you think about making a clickable prototype of this for some testing? I would like to know whether users find these interactions intuitive.

Interested in what others think.

**Comment by doruskova** [comment]
@mcarrano I agree. And I'll prepare the prototype for testing next week. 
@ajacobs21e Can you send me your examples? It would be awesome.

**Comment by doruskova** [comment]
@nlcwong Can you send me your examples? I think that Allie has the same requirement, but I want to be sure that it covers your use case too :)

**Comment by doruskova** [comment]
@nlcwong @ajacobs21e @mcarrano @aprilma419 Hey all, I've recently finished the testing of breadcrumbs with multilevel-drill-down menu and I have some interesting inputs that I'd like to solve somehow.

I'll share with you the highlights: 
- The multilevel breadcrumbs work well (yay!) in general. 
- It wasn't confusing for the participant to use (...) three dots to open the dropdown with previous categories. 
- Selecting the checkboxes was easy and clear to them. 
- _The issue which showed up:_ the hierarchy of hidden breadcrumbs in a dropdown is not clear. They expected to see some visual indicator (e.g. arrow) that shows the connection/hierarchy between sub-categories. They thought that all sub-menus are in the same level of deep. Even though they went through a hierarchy.
- They would like to see selected items somewhere separately. Because it can be difficult to remember everything. One of my participants suggested having a badge with selected items. 
_My note: I think that we should have a consistent approach for selected items. Filtering is easy because you select the items and see the action immediately. But, when you have to take an action above all selected items > it can be a problem._ 
- They mentioned that using checkboxes in breadcrumbs is not usual. It's against the purpose of breadcrumbs. 
- They were ok with "Show more" in a dropdown with sub-categories. When they know what they're looking for > they are willing to go through a lot of submenus. 

So, I think that the only thing we need to figure out is: **selected items** (is it needed for the initial component?) and **visual indication** **for hidden breadcrumbs.**

**Comment by ajacobs21e** [comment]
@doruskova What about something like this for the hidden breadcrumb hierarchy?
![image](https://user-images.githubusercontent.com/6415742/88331904-54cc0f00-ccf3-11ea-8b27-5ea48c8a0b17.png)

Something that shows hierarchy but is only nested by a few pixel each time so we can show more of each level

**Comment by aprilma419** [comment]
@doruskova I've heard the same comments on this issue from our developers as well, what I did was using arrows instead of a list to indicate the hierarchy of sub-levels in the dropdown as the image showed.

<img width="521" alt="Screen Shot 2020-07-24 at 10 19 46 AM" src="https://user-images.githubusercontent.com/44431015/88355464-3b7c9e80-cd97-11ea-9e71-e2043a963034.png">

> * _The issue which showed up:_ the hierarchy of hidden breadcrumbs in a dropdown is not clear. They expected to see some visual indicator (e.g. arrow) that shows the connection/hierarchy between sub-categories. They thought that all sub-menus are in the same level of deep. Even though they went through a hierarchy.

**Comment by doruskova** [comment]
Thank you so much for your ideas! I created the screen with possible designs [here](https://marvelapp.com/prototype/66b0059/screen/71536522). I would like to keep the simplicity of collapsible breadcrumbs as much as possible. Let me know what you think.

**Comment by doruskova** [comment]
@mcarrano I created the version we're talking about yesterday. The hidden breadcrumbs should appear in the same window. Here's the link https://marvelapp.com/prototype/66b0059/screen/71597941
It includes two versions. 
- The first one with a button on the right side. The second without the button. 
- Version A shows expanded breadcrumbs and current categories from the last parent node. 
- Version B shows just expanded breadcrumbs. 

My preference is the second version without the button and B version that shows just hidden breadcrumbs. The hidden breadcrumbs have a caret indicator, so I think that the hierarchy is more clear. Let me know what you think about it @ajacobs21e @nlcwong @aprilma419

**Comment by ajacobs21e** [comment]
Thanks @doruskova ! I agree the version without the button makes more sense. It gives more room for longer labels. I added a comment in marvel, if it doesn't make sense I can draw out what I'm thinking.

**Comment by mcarrano** [comment]
@doruskova I had similar feedback as @ajacobs21e . See my comments in the Marvel deck. If it's confusing, then maybe the 3 of us can jump on a call. Thanks!

**Comment by doruskova** [comment]
@mcarrano @ajacobs21e @nlcwong @aprilma419 I'm adding the mock that we discussed the last time https://marvelapp.com/prototype/66b0059/screen/71809215
Please, let me know if this approach will work for you. I used dropdown for multiple breadcrumbs, so you can see the whole structure and go back every time you want. Also, it should be possible to select a parent node with all children from the menu, but not from dropdown-breadcrumbs.

**Comment by mcarrano** [comment]
This looks great @doruskova . I just left a couple of questions/comments. I have reservations about placing this pattern inside of a dropdown as shown in the last example, but I don't have a better idea. I think it works. What do others think?

**Comment by aprilma419** [comment]
@doruskova These are awesome. Just wondering are we going to have an action link or button somewhere on this dropdown component? For example, like a “Move here" button.

**Comment by mcarrano** [comment]
That could be useful. @doruskova perhaps look at how Google does this? I think we could add an optional action at the end of the menu or something like that.

**Comment by aprilma419** [comment]
Hi Matt@mcarrano, I have a question about the breadcrumbs usage for this tree menu. As for my example, I have regular long breadcrumbs displaying on a header of a page(the image below), will the new collapsible breadcrumbs fit in this header? Or it just fit in a tree menu?

![image](https://user-images.githubusercontent.com/44431015/89869649-3ae16600-dbe7-11ea-8b40-548277967a33.png)

**Comment by mcarrano** [comment]
@aprilma419 We were not considering this as a general purpose extension to the Breadcrumb component. If this is something you need, I recommend opening a new design issue for it and we can consider it. Thanks.

**Comment by doruskova** [comment]
@mcarrano @aprilma419 Thanks for bringing this question about action items in a breadcrumb menu. I've explored the Google way, but the problem is that they don't show something like this in a breadcrumb. They use the context menu that triggers the "Move to" action and then a simple drill-down menu appears. 

This breadcrumb/dropdown shows the path you went through. If I change something in this dropdown > break the current breadcrumb. Also, you need to select/check the node to be able to click on the "move" button. I think that breadcrumbs should be used for navigation.

But, if you meant the main drill-down menu, then I've tried to apply the same approach and made some sketches for it. It looks more complex. https://marvelapp.com/prototype/66b0059/screen/71918537
I'm just wondering what other actions could be applied there.   

However, can we agree that the main component is finished @ajacobs21e @nlcwong ? It definitely needs to be reviewed with dev (dropdown in a dropdown and search bar behavior) and this action item is an additional feature.

**Comment by mcarrano** [comment]
I was thinking about adding a footer to the menu like for the Google Move To action here:

![Screen Shot 2020-08-11 at 1 24 32 PM](https://user-images.githubusercontent.com/6619860/89928748-4aa47e80-dbd6-11ea-9783-494a9b37581b.png)

But one could argue that this behavior could apply to any select menu and not just a drill down so I'd rather solve in a more general way. @aprilma419 if this is something you need, feel free to open a new issue. But I'd rather not complicate the drill-down component with this functionality.

**Comment by aprilma419** [comment]
@mcarrano Actually we need both drill-down menu and multi-level breadcrumb components for our designs. As for the drill-down menu, I think the dropdown with the action button at the footer works for our case as well. 

I will open a new issue about the breadcrumbs, not only for Keycloak, I'm also summarizing breadcrumb usage for Middleware Integration apps, which have similar problems here.

**Comment by doruskova** [comment]
@mcarrano I agree with you. I've added the version where the button is at the bottom https://marvelapp.com/prototype/66b0059/screen/71918537

But, as you mentioned, we should consider and explore this more to make action items like this flexible and suitable for other types of menu.

**Comment by mcarrano** [comment]
Thanks @doruskova This looks great. 

@mcoker @christiemolloy Wanted to give you a preview of this as we were discussing our overall approach to menus. Please see the last comment regarding adding an action footer to a menu. I think this could be a useful option. Thoughts?

**Comment by christiemolloy** [comment]
Thanks @mcarrano this helps a lot!

**Comment by doruskova** [comment]
@mcarrano I played with breadcrumbs and I identified breadcrumbs problems for each option [here](https://marvelapp.com/prototype/66b0059/screen/72512507)
And created possible solutions for each menu [here](https://marvelapp.com/prototype/66b0059/screen/72512506)

**Comment by mcarrano** [comment]
Thanks @doruskova . In looking at these, I have a preference for the third option (collapsible) but It might make sense to mock these up in code to see how they feel. Other thoughts?
