### ISSUE TITLE
Horizontal card

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design#872]
Requesting a card that could show an image, logo, or video side by side with text, resulting in a card that is wider than it is tall. 
Design by @samliville
https://sketch.cloud/s/jeL2W

**Comment by mcarrano** [comment]
@mcoker any reason we can't create cards like this now?

**Comment by mcoker** [comment]
@ajacobs21e since the card's title/body/footer elements don't have to be a direct descendent of the card component currently, you could create a card component wrapper, then use a layout inside the card and place the card's title/body/footer elements somewhere in the layout.

Here's an example using HTML/CSS https://codepen.io/mcoker/pen/qBbmJJZ and one using react https://codesandbox.io/s/awesome-panini-rfxeh

While that works, it's not something we have specific support for, so it could potentially break as we make updates to the card layout.

**Comment by mcarrano** [comment]
Thanks for investigating @mcoker . So given that, what would you recommend here? Should we add a horizontal variant of the Card component to handle this layout option?

**Comment by mcoker** [comment]
@mcarrano potentially. It sounds like we should solve it in a way that lets users use any layout they want in a card (as opposed to just a horizontal layout).

The problem currently is that we need to make some assumptions about how users will build their card so that we can apply the correct layout and spacing. Currently we assume this basic structure, with the exception that someone could just use "card" as a generic wrapper and put anything they want inside, but then we assume they aren't using the card-header, card-title, card-body, or card-footer.

```
card
  -> card-header
    -> actions, title, etc
  -> card-title
  -> card-body
  -> card-footer
```

In the demos I included, I built it like this - which works, but could break since we make the assumption currently that card-header/body/footer will be a direct child of "card"

```
card
    -> grid
        -> grid-column
            -> // custom content - the image
        -> grid-column
            -> card-header
            -> card-body
            -> card-footer
```

I'm curious if you or @ajacobs21e could include a few use cases for custom card layouts like this using the card? Also keeping in mind that as a card, it can take on any of the card states - like hoverable, selectable (with the blue border, not the checkbox in the header), flat. And how we might want to include the structural elements inside it (card-header/title/body/footer).

**Comment by ajacobs21e** [comment]
@mcoker here are some examples: https://www.sketch.com/s/1c8ae19e-07bb-4e92-9c14-057d9ca9b251/a/3gPoRr
Those all have the text on the right but it could be on the left as well.

**Comment by gdoyle1** [comment]
As shared today during the PF design share meeting, @mcarrano OpenShift has a similar need for a horizontal card! We would be looking to get a horizontal card component like this in by our 4.8 release, which is planned for November/early December. 

I've attached the specifications here to what we'd need for OpenShift and possibly how it could apply to other product cases as well!

![horizontal card example](https://user-images.githubusercontent.com/30870144/92633225-76cc2180-f2a0-11ea-8a61-37d1a63ea000.png)

**Comment by mcarrano** [comment]
Thanks @gdoyle1 I've bumped this up to our 2020.15 release (mid November). Is this something you think you can take the design lead on?

**Comment by gdoyle1** [comment]
@mcarrano Yup that's fine with me!

**Comment by gdoyle1** [comment]
Incorporated the web cases from above here too!
Marvel: https://marvelapp.com/prototype/5e55293

**Comment by mcarrano** [comment]
Have opened two new issues to begin core implementation:

* Introduce a collapsible card: https://github.com/patternfly/patternfly/issues/3554 This feature will be available for any card and is required to support the OpenShift designs included in the mocks.

* Add a horizontal card demo: https://github.com/patternfly/patternfly/issues/3555 Basic implementations of the horizontal card show not require direct changes to the card component itself and can be addressed via creating a new demo.

cc: @gdoyle1 @mcoker
