### ISSUE TITLE
Modify the Empty State small variation to be compact/smaller

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-design#885]
In the insights dashboard that I have been implementing (designed by @kybaker) the design spec includes an empty state where the body and secondary action buttons are 14px. There is also a smaller margin-top on the secondary-actions:
<img width="405" alt="Screen Shot 2020-03-24 at 4 11 03 PM" src="https://user-images.githubusercontent.com/20118816/77474315-42959f00-6ded-11ea-880f-bfbe31442260.png">

I believe this could be a common use case where empty states are used in cards. If we went ahead with this, ideally it would be included in the breaking change release.

There is also a potential use case to remove padding on the empty state for when it is used in cards etc. 

Thoughts? @kybaker @mmenestr

**Comment by mmenestr** [comment]
**Here is my proposal:** https://marvelapp.com/prototype/7c5cdhd/screen/72928590

Basically, instead of modifying the small empty state which is mostly used in tables and wizards, where there is enough space, I would add a new variation called extra-small, that could be used in cards and not have any icons.
I modeled the specs after the current implementation of the card empty states in the Insights dashboard!

**Comment by mcarrano** [comment]
This looks good @mmenestr . My only question/concern is how this works with the overall structure of the card that has a header, body, and footer and whether this makes more sense as a variation of the Card rather than as a new empty state pattern. @mceledonia @mcoker please also take a look.

**Comment by mmenestr** [comment]
@mcarrano You could have two options:
1. Either keep the card header, and just add the empty state to the body:
![image](https://user-images.githubusercontent.com/51165119/93892191-403bd100-fcba-11ea-8a88-0dc92425621a.png)

2. Or have no card header, just a card background with an empty state inside it.
![image](https://user-images.githubusercontent.com/51165119/93892150-30bc8800-fcba-11ea-9cb7-b3d8b380445e.png)

Since there are these two variations I think it would make sense to make it an empty state, and not just a new card variation because it's something you're placing in a card - and it may or may not be the only thing on the card.

**Comment by mcoker** [comment]
@mmenestr your proposal for this as an xs variation of empty state sounds perfect.

**Comment by mcarrano** [comment]
In that case, I think we can move this forward. I've created a new core issue here: https://github.com/patternfly/patternfly/issues/3513 Thanks for your work on this @mmenestr .
