### ISSUE TITLE
Empty State/Create Card Variation for Card View

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design#886]
We have found the need for an “empty state” variation of the card component to be used in card view. 

An implementation used to exist in a past version of Fuse Online, and we are looking to add this behavior back in. When migrating to PF4 we swapped the empty “create” card for a primary button in the card view toolbar, but feel that it is not as discoverable/intuitive. 

This empty state should visually align with the rest of the cards in a card view grid, but still be distinguishable. The empty card should always show as a card in the grid—adding a new card will not replace the contents of this empty card, but rather create a new card. The designs should address the styling of the empty card and its contents, and the recommended placement of the empty card within the card view grid. Designs should consider use on both gray and white backgrounds. 

Older iterations below:

![image](https://user-images.githubusercontent.com/46571616/86054422-1d39b200-ba28-11ea-9d3a-6e2e70d1a092.png)
![image](https://user-images.githubusercontent.com/46571616/86054446-29257400-ba28-11ea-8656-2b0cf1cea632.png)

CC @mcarrano @mceledonia @amysueg @tiffanynolan @mviang

**Comment by bdiring** [comment]
We have a use case for this in a "Create project" wizard for Migration Toolkit for Applications: 
![image](https://user-images.githubusercontent.com/54444091/86056028-c5507a80-ba2a-11ea-8cfe-0ed0f1e5fc80.png)

**Comment by katierik** [comment]
I have used this pattern in a concept design for users being able to choose "favorite reports" (wireframe below)
![Xnip2020-06-30_07-46-26](https://user-images.githubusercontent.com/23172038/86122428-d2f71600-baa5-11ea-8cdc-b8b0ba51696f.jpg)

**Comment by mmenestr** [comment]
Just created these mocks for different possibilities https://marvelapp.com/prototype/f869h61
Essentially, we can either use the already created "cards" provided by PatternFly **OR** we could have a new card variation exclusively for this use case. Not sure if these are variations that could already be made with the current card implementation or if it would have to be a whole new card.. Either way though, I propose we use the newly implemented xs empty state for these cards, instead of doing something completely custom. That will also allow for the flexibility of including or not including headers, bodies and buttons based on different use cases.

Let me know your thoughts! @lboehling @mcarrano

**Comment by mcarrano** [comment]
Thanks for the options @mmenestr . I would be in favor of building this out of existing card + xs empty state, but interested to hear what others thinks.

**Comment by lboehling** [comment]
Thank you @mmenestr! 

Yeah, I think the gray background without the dashed line could be confused for a disabled card. I'm also in favor of building this from the existing card + xs empty state too. Looking at the designs, I think I prefer the variation without a header since the action is repeated almost directly below in the button, and since there is pretty limited space. I'm also wondering if the primary button should be changed to a secondary or link button, since users would probably only click on this button IF another card didn't meet their needs. 

@mcarrano @mceledonia

**Comment by mmenestr** [comment]
@lboehling to clarify, since the idea is to use an xs empty state, those capabilities/choices would be built in already. So you could choose if you want to keep or remove a header, you could choose what button type you wanted etc! I was just showing different variations in the mock but we don't necessarily have to specify which one one should use, since they're all capabilities of the xs empty state!

**Comment by mmenestr** [comment]
Here is the final proposal with all the details @mcarrano: https://marvelapp.com/prototype/f869h61/screen/74368154
Please let me know if i'm missing anything!

**Comment by mcarrano** [comment]
These look good to me @mmenestr .

@mcoker can you give this a look and let us know if you see any issues? My assumption is that we would just add this to the Card View demo leveraging existing Card and Empty state components. But let me know if you see anything that would require more rework.

**Comment by mcoker** [comment]
@mcarrano @mmenestr looks good to me. One thing is that the empty state is vertically centered in the card. This won't happen automatically since card contents are aligned to the top, and while the empty state component's content is horizontally/vertically centered in the empty state component, when placed in a card the empty state is only as tall as it needs to be to hold it's content. It ends up looking like this:

<img width="1125" alt="Screen Shot 2020-11-16 at 5 59 41 PM" src="https://user-images.githubusercontent.com/35148959/99322655-05779480-2836-11eb-9b29-6b37753f9fda.png">

We could fix that a couple of ways:
* Change the empty state component to try and consume the height of the box it's in. Then the content in the empty state component will be vertically centered if the empty state is taller than the content inside.
  * This could be a breaking change if the empty state component is currently used in a box that is taller than the empty state component. Maybe that's a good thing/bug fix? For example, you would go from this

<img width="1291" alt="Screen Shot 2020-11-16 at 6 07 31 PM" src="https://user-images.githubusercontent.com/35148959/99322961-b9791f80-2836-11eb-9a32-9d6a3ec44bd1.png">


to this

<img width="1343" alt="Screen Shot 2020-11-16 at 6 07 41 PM" src="https://user-images.githubusercontent.com/35148959/99322967-bc741000-2836-11eb-9064-5318fcf96045.png">

* Use a bullseye layout in the card, with the empty state as the child of the bullseye layout. This would be the least intrusive way of doing that, though it would place more responsibility on product devs to make sure they're using that layout. I guess it also comes with the benefit of not using it if a product wants the empty state card to be top aligned.

**Comment by mcarrano** [comment]
@mmenestr What are your thoughts? I don't so much mind that it aligns to the top like this, but if we want it to vertically align to the center, perhaps we can just construct the demo with a bullseye layout like you suggest @mcoker . That will at least provide other developers with an example of how to construct this.

**Comment by mmenestr** [comment]
Yeah @mcoker I actually want empty states to remain aligned to the top when they're not inside a card, so I think for this use case, using the bullseye layout for inside a card would be the best way to go!

**Comment by mcarrano** [comment]
Sounds good. I've opened a new core issue here and will add to a future milestone: https://github.com/patternfly/patternfly/issues/3687
