### ISSUE TITLE
Add form sections to documentation

### ISSUE THREAD

**Issue by bmignano** [patternfly/patternfly-design#889]
In OpenShift, we need the ability to box off fields in a form that make up a distinct elements within the form. We investigated using indentation as a solution, but the boxes create a more clear hierarchy and are more visually apparent. Attached are two (low-fidelity) mocks of where we would use this feature.

FYI @beanh66 @andybraren @cshinn 

![create-secret](https://user-images.githubusercontent.com/40238481/57883777-374d0c80-77f5-11e9-93e1-ce7459e6f648.png)
![create-network-policy-FORM](https://user-images.githubusercontent.com/40238481/57883781-3916d000-77f5-11e9-88ad-e1bbcde284ef.png)

**Comment by itsptk** [comment]
Just to mention, the existing Accordion styling seems like decent option for conveying general grouping as well. @lizsurette @mceledonia 

![image](https://user-images.githubusercontent.com/54860125/87449628-6adb2080-c5cb-11ea-88fc-c3172232f3f9.png)

**Comment by lboehling** [comment]
Apicurio Studio API Editor has a lot of repeating/nested field groups. In the updated UI, each card will have a read-only/edit mode (edit mode enabled on card click) and the contents of these cards can have varying levels of grouping complexity. I used a divider line to separate groups with a few repeating fields and an expandable row to separate more complex groupings (I removed the expanded row left blue border because the left blue border is also used to indicate an active/edit enabled card).  https://marvelapp.com/prototype/11ib55a4/screen/69945070

**Comment by TheRealJon** [comment]
@itsptk @mcarrano I think that this enhancement could replace #904 if we add a few more considerations. IMO, the OpenShift Operand creation forms should use something like what is proposed here instead of the `Accordion` component. Here are a few constraints to consider for use in the Operand creation form (I'll call the component a 'fieldset' for easy reference):
- A fieldset shall support an optional top-level legend (a caption for the fieldset)
- A fieldset legend shall support a tooltip or popover interaction
- A fieldset shall support arbitrarily deep nesting of further fieldsets (within reason)
- A fieldset shall support optional collapse behavior

Something that also might need a bit more discussion is the difference between a plain fieldset and an 'array' fieldset. IMO, there is a big enough difference between these two concepts that they require their own set of considerations and possibly even separate modifiers or components. I can expand more on this if needed.

**Comment by maryshak1996** [comment]
@mcarrano @lboehling @bmignano I took another stab at this stuff, given the new use cases provided. 
My initial thought is -- can the form grouping needs be supported with what currently exists with the tree view, since that allows for nesting, multi-level drill dow, and indentation?
I did also play around with something very similar to what @lboehling included in her Apicurio mocks, and it seems like it might fit the other use cases mentioned here too. I mocked up two of the openshift cases, as well as re-mocked the apicruio case here: https://marvelapp.com/prototype/920c0bj

**Comment by mcarrano** [comment]
@maryshak1996 I don't see the tree-view as related to this since that's something more like a menu vs a form container. That said, I think you basic approach works, however I'm not sure about putting actions inside of the caption/header area. Do others think they belong there or as part of the body of the form inside of the section?

@TheRealJon @itsptk please also take a look and let us know if this would meet your needs, too.

**Comment by lboehling** [comment]
Adding some more design explorations here (using the use cases provided in this issue): https://marvelapp.com/prototype/5dfae4f/screen/72667640

I wanted to explore what these repeating, nested, and/or collapsing fieldsets could look like if we used a combination of indentations and divider lines, and relying less on borders to block off entire sections. 

@mcarrano @maryshak1996 @bmignano

**Comment by itsptk** [comment]
Of note is that these forms in OpenShift can be fairly deeply nested today. Here is an example I quickly found that has 4 levels deep. I wasn't sure if this particular request was intended to handle nested sections as well.

![image](https://user-images.githubusercontent.com/54860125/92813796-eec54500-f38f-11ea-9d20-7f544061213c.png)

**Comment by TheRealJon** [comment]
Looking at @itsptk 's screen cap, I realized I forgot a constraint:
  - A fieldset shall support optional help text

Also, one thing that I think works really well with the current implementation (using the accordion component) is the blue border on the left. It makes the hierarchical structure very apparent without overwhelming the page with borders. I'm wondering if we could do something similar for the new fieldset. Maybe just use a  different border color?

**Comment by lboehling** [comment]
Updated designs can be found here: https://marvelapp.com/prototype/5e57if3/screen/72963171

**Comment by mcarrano** [comment]
The designs are looking good @lboehling . @TheRealJon @itsptk @maryshak1996 @mceledonia @bmignano does this also work for you?

**Comment by bmignano** [comment]
These look great to me, thanks @lboehling @mcarrano !

**Comment by maryshak1996** [comment]
@mcarrano @lboehling I think that this is looking great :)

**Comment by mcarrano** [comment]
I have opened https://github.com/patternfly/patternfly/issues/3557 to begin implementation in PF core. Thanks for your work to bring this to closure @lboehling !
