### ISSUE TITLE
Modal dialog positioning: support top positioning

### ISSUE THREAD

**Issue by ziccardi** [patternfly/patternfly-design#890]
With PF4, the modal dialogs are now centered both horizontally and vertically, while with PF3 they were put on the top of the page.
A discussion about this has already been done here: https://github.com/patternfly/patternfly/issues/2980

However, having the Dialog centered has its drawbacks too: if you have some expanding content that makes the dialog expand vertically, you will see the dialog move up when the expandable content is expanded and down otherwise.

That can be noisy if for example you have a DataList with expandable items into the Dialog.

By aligning the Dialog at the top as it used to be, that didn't happen, because the dialog was nicely expanding at the bottom.

So, in the end, while I agree with the decision behind centering the dialog by default, I believe it would be very beneficial to hava a `position` attribute to allow to select the old behaviour if needed.

**Comment by mceledonia** [comment]
I'm alright with changing our default behavior over back to this given the issues with center alignment that @garrett has outlined above. 

The measurements you've suggested sound good to me, `spacer--xl` for desktop and `spacer--sm` for mobile.

@mcarrano were there any issues with the PF3 approach? I believe the change to centering was more of a quick stylistic decision rather than one which underwent due consideration. Will this be a breaking design/code change? Given that it moves the dialog towards the top of the screen, I'm not sure it would be breaking from a design perspective. Similar to how we don't consider reducing spacing a breaking change. 

@mcoker Any thoughts on if that would be breaking from a code perspective?

**Comment by mcoker** [comment]
@mceledonia it's not a breaking change in the code.

**Comment by mcarrano** [comment]
It's technically not a breaking change, but I would still want to offer this as an option rather than changing the default behavior globally. @kybaker do you have any recollection of why we chose to center align the modals in PF4?

**Comment by ziccardi** [comment]
@mcarrano I believe the reasons are described here: https://github.com/patternfly/patternfly/issues/2980#issuecomment-625338553
My 2 cents: I too prefer to have an option rather than changing the default behaviour.

**Comment by mcarrano** [comment]
I've opened https://github.com/patternfly/patternfly/issues/3405 for core implementation.
