### ISSUE TITLE
Expand/Collapse All for DataList and Tables

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#905]
Introduce an expand/collapse all feature to the Table component. This will allow the user to expand and collapse all rows of an expandable table in a single click. Designs here: https://drive.google.com/drive/folders/12KAQ-n_QfEdP8LCVV-RZpILVFBkIhXMK

cc @mcoker @LHinson

**Comment by lboehling** [comment]
@mmenestr @mcarrano Apicurio Studio's current implementation has collapse/expand all for the sections in the api editor. This context menu is accessed via right-click on the arrow icons. This behavior isn't within a data list or table, but thought it might be a good reference! 

 ![Screen Shot 2020-08-25 at 3.58.20 PM.png](https://images.zenhubusercontent.com/5cf531f8d8501ed6b9d4c7ad/857c06f5-99ad-4954-8f33-c7cdb9982cb2)

**Comment by mmenestr** [comment]
I've mocked up 3 different options to get feedback on!
**[Option 1:](https://marvelapp.com/prototype/91had53/screen/72599164)** Action button in toolbar
**[Option 2:](https://marvelapp.com/prototype/91had53/screen/72599165)** Action button in toolbar kebab 
**[Option 3:](https://marvelapp.com/prototype/91had53/screen/72599166)** Arrow in toolbar, left of the bulk select icon

I personally like Option 3. It also makes me re-evaluate the design for the table expand all, where I had the arrow in the table header instead of the arrow in the toolbar. 

I feel like Option 3 would actually work well for both tables and data lists, and would keep the design consistent, since an arrow in a table header can't be replicated in data lists since they don't have headers. It also keeps the actions that affect all items in the table together, and vertically aligned with the "single row" actions! Here's a [re-mock](https://marvelapp.com/prototype/91had53/screen/72599384) of the table with an expand all in the toolbar as well.

@mcarrano let me know what you think!

**Comment by mcarrano** [comment]
@mmenestr I agree with you that Option 3 is the best choice and I like that it will give us a consistent approach for either lists or tables. The only thing I'd like to reconsider is the icon. I feel like the ">" is confusing because it normally implies that the content following it will be expanded which is not the case here. What about using the Expand and Collapse icons like in @lboehling 's example? Also, if I click "Expand all" does the icon toggle to "Collapse all?" What happens if the user clicks expand all and then manually closes some rows? What does the icon do?

@mattnolting can you also take a look at this? Any reason why inserting an item, in this case a plain icon button, in front of the bulk selector would be a problem?

**Comment by maryshak1996** [comment]
@mmenestr I definitely agree that option 3 seems like it would give the most consistent experience between lists and tables :)

**Comment by mmenestr** [comment]
@mcarrano I see what you're saying about the icons, but no matter what icon we use, I feel like the same thing could be said! From an icon stand point alone, I personally think the arrow makes more sense because it's in line with what's already being used in the rows themselves. Whereas the icon in Lucia's screenshot is looks more like an expand window icon to me - but maybe that's just me! Another idea could be to do the double arrow which Mary and I had used when we carried out the user testing for this:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/51165119/92619288-5051ba80-f28f-11ea-88c3-1840bddf1a6e.png">

Also in terms of the functionality, I had written out this doc to outline how it would work functionality wise:
https://docs.google.com/document/d/1zEtmy0z4DfTDwZNei-Wgd-04ox8H3NQxA8z18-109QU/edit# 

In the case you asked about, the arrow would remain downward facing (collapse all button), even if someone manually closed a row, because some rows would still be open. But if someone were to manually close ALL rows, it would become the "expand all" button again

**Comment by mmenestr** [comment]
Here is what it could look like using the patternfly "expansion" icon though!

![image](https://user-images.githubusercontent.com/51165119/92620027-319ff380-f290-11ea-918c-e758c5e7441f.png)

**Comment by lboehling** [comment]
I agree that the icon should be consistent with the other "expand" caret icons used in the rows, but I also think it is kind of difficult to differentiate the expand all from the row expansion at a glance. What if we used an enclosed caret? It would be distinguished from expand single row, but would still use essentially the same icon. 
<img width="62" alt="Screen Shot 2020-09-09 at 12 05 31 PM" src="https://user-images.githubusercontent.com/46571616/92624096-1aafd000-f295-11ea-945d-5296c3af62b9.png">

**Comment by mmenestr** [comment]
Here are the [poll results](https://www.strawpoll.me/20988259/r) from the PatternFly meeting:
![image](https://user-images.githubusercontent.com/51165119/94030487-df7cc900-fd8b-11ea-9eaa-4e522bb84fe5.png)

Seems that most people liked the classic arrow, mostly based on a visual and consistency stand point!

@mcarrano Not sure what to do about the placement! I personally would leave it as is because I that the behavior can be easily learned - so even though it might seem confusing to some, as soon as they clicked on it they could see what it actually does right away!

**Comment by mcarrano** [comment]
I am OK going with this approach for lack of a better answer. Agree that the behavior will be easily learned and having a tooltip will help. Since this is just an element in the toolbar, it will be easy to change or customize. @trahman73 not sure if you saw this at the PF design share this morning, but if not, please take a look at this design. Do you feel like this will satisfy your Ansible requirements? If yes, I will move this along to development.

**Comment by trahman73** [comment]
@mcarrano Thanks Matt, yes I did see it this morning at design share and feel that this would cove the Ansible use cases nicely.

**Comment by mmenestr** [comment]
In that case @mcarrano, here is the final proposal with all the details and explanation of the functionality:  https://docs.google.com/document/d/1zEtmy0z4DfTDwZNei-Wgd-04ox8H3NQxA8z18-109QU/edit#

And here are the basic mocks again: https://marvelapp.com/prototype/92g763j/section/1136353

**Comment by mcarrano** [comment]
@mcoker @mattnolting can you take a look at the designs posted above? If we go with this approach of adding a collapse/expand all button to the toolbar, will this require any core changes or can this be moved directly to React?

**Comment by mcoker** [comment]
It looks like you should just be able to drop the button in an icon group with the bulk select

<img width="832" alt="Screen Shot 2020-09-24 at 2 48 26 PM" src="https://user-images.githubusercontent.com/35148959/94192831-18dd3380-fe75-11ea-9182-b6c2426e8488.png">

**Comment by mcarrano** [comment]
So can this just be handed off directly to React in that case @mcoker ?

**Comment by mcoker** [comment]
I think so. WDYT @mattnolting? Do you think an icon group works there or do we need unique element for the expand all action?

**Comment by mcarrano** [comment]
Per discussion on 9/30, core work should not be required and therefore I have opened the following issues directly in React to begin implementation:

Add expand/collapse all to Data list: https://github.com/patternfly/patternfly-react/issues/4942
Add expand/collapse all to Table: https://github.com/patternfly/patternfly-react/issues/4943

**Comment by mattnolting** [comment]
> I think so. WDYT @mattnolting? Do you think an icon group works there or do we need unique element for the expand all action?

@mcoker I think the `icon group` works, as well as `pf-m-space-items-none` 👍
