### ISSUE TITLE
add active state to patternfly components

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-design#907]
This request is to add active state to patternfly components in addition to existing states for hover and focus.

Perhaps there's an official design stance on why active state is ignore. If so please clarify.

**Comment by doruskova** [comment]
@mcarrano I'm adding an update on the active state for buttons and links :) [Mock is here](https://marvelapp.com/prototype/14210469/screen/76778608)

I've added a darker background or border color for buttons, except for the tertiary button because it's already black and needs to be different from a disabled state which is filled with a grey bg. 
The question is an inline link because we can use default colors from browsers (purple color) or use our own styling for simple links. Do we want to leave it on a browser? Currently, we're overriding the style with `#0066cc`.

**Comment by mcarrano** [comment]
@doruskova I think these look good. Not sure what to do about the tertiary button, however. Maybe add just a very pale gray fill? I'm not so concerned about active states for link buttons. But there is a related issue here: https://github.com/patternfly/patternfly/issues/3726 Maybe see if that helps with an answer.

@mceledonia @mcoker can you also take a look at this? Do we need to address any components other than buttons?

**Comment by doruskova** [comment]
@mcarrano mock updated with a filled tertiary button for the pressed state. https://marvelapp.com/prototype/14210469/screen/76778608

**Comment by mcarrano** [comment]
Looks good to me @doruskova . Thanks.

**Comment by mcoker** [comment]
@mcarrano @doruskova these look good to me. Just to confirm, if we update the inline link button, does that imply we'll update the global link styles to have the same active state styling?

**Comment by mcarrano** [comment]
I have opened https://github.com/patternfly/patternfly/issues/3898 to implement these styles for Buttons. We can also consider other components later, as needed. Thanks for your work on this @doruskova

**Comment by mcarrano** [comment]
No need to add to documentation or Sketch library. Will close.
