### ISSUE TITLE
Introduce Dashbars

### ISSUE THREAD

**Issue by abichen** [patternfly/patternfly-design#913]
OpenShift is looking to implement dashbars that provide users with meaningful summaries of the content below it. We're hoping to contribute this back downstream and introduce it to PatternFly. 

![Screen Shot 2020-08-20 at 1 44 55 PM](https://user-images.githubusercontent.com/66273283/90806679-59ccb000-e2eb-11ea-8846-3252fc3dddd0.png)

**Details**
- [Doc](https://docs.google.com/document/d/1LV7fe-xNDC7S5DcF2qLohGxUMU1zDkLuIgz0d870JHc/edit#)
- [Marvel](https://marvelapp.com/prototype/5c0di4c/screen/71842376)

**Comment by mcarrano** [comment]
@beanh66 @jcaianirh is there anything more you can tell me about this requirement? I discussed today with @mceledonia and @mcoker and it seems like this is something that can be built today using existing PF layouts and components. We could potentially create a demo if that's useful, but other than that, we are not sure if there is a PatternFly action required.

**Comment by mceledonia** [comment]
@mcarrano @mcoker 

I wanted to loop back around on this, can we build this with existing components? This seems like it could be a demo of our dashboard layout, showing how it can be used in a more minimal fashion.

**Comment by mcoker** [comment]
@mceledonia it looks like it - the only thing is the card content isn't an out of the box card, a user would have to use custom styles for that. We have an issue to build some dashboard card demos,  and looks like it would cover this use case. https://github.com/patternfly/patternfly/issues/3278 

IIRC we were going to build the demos with custom styles that serve as examples of how to lay out dashboard cards, as opposed to layouts that are part of PF.

**Comment by mcarrano** [comment]
I will add to the backlog as a potential demo we could create using dashboard cards.

**Comment by mcarrano** [comment]
@mceledonia @beanh66 @gdoyle1 Is this something that is still needed by OpenShift? If not I'd like to close it out. The issue has been hanging around for a while without any activity. If it's still needed, I can get it on the roadmap, but I don't really see any barriers to making this.

**Comment by gdoyle1** [comment]
AFAIK we did still want to use a component like this within OpenShfit and OCM .. I believe ACM also wanted to. I think what would be most helpful is having a demo and some sort of guidelines around when to use something like this! @mcarrano

**Comment by mcarrano** [comment]
OK. I will keep this open. I see this as basically just a mini-dashbaord. @mceledonia I am going to assign you so perhaps you can consider this use case while you are looking at dashboard demos here: https://github.com/patternfly/patternfly-design/issues/752

**Comment by doruskova** [comment]
@mcarrano Adding dashbars with responsive layout.
Basic - https://marvelapp.com/prototype/d642i6g/screen/84703403
With chart - https://marvelapp.com/prototype/d642i6g/screen/84703118
Expandable - https://marvelapp.com/prototype/d642i6g/screen/84702896

**Comment by doruskova** [comment]
@mcarrano Hey Matt! I'm adding an update on the carousel for dashbars. Here's the link on a marvel mock that reflects a dashbar with a carousel on a desktop and then on mobile. https://marvelapp.com/prototype/d642i6g/screen/84887918

My opinion is that it's just too much on a desktop version. I can't imagine using it and scrolling through so many options even though it has "only" 2 pages. It can have an impact on accessibility because it's moving and the content may easily be missed. I don't know any use-case where we could apply it now. I can imagine this carousel, for instance, on some onboarding screen or advertisement (e.g. discover more categories or learning courses). Regardless, it works as a responsive solution for a mobile version. But, do we want to spend time on a mobile version when people use the desktop the most?

**Comment by mcarrano** [comment]
Thanks @doruskova Per our discussion today, I am going to keep this issue open but place it on hold unless and until we have a specific request for a scrollable dashbar. Thanks for all your work on this.

**Comment by doruskova** [comment]
@mcarrano Do we want to have a demo for dashbars as well? Or is it only for a dashboard?

**Comment by mcarrano** [comment]
@doruskova I think that we should fold a dashbar example into the dashboard demo. Did you include one in your dashboard demo mockups?

**Comment by doruskova** [comment]
@mcarrano No, I didn't because it's almost always placed above the table or data list. The exception is in OpenShift where it's used above a dashboard. I can add it into a demo mockup. But, it's doesn't reflect the most usual use case.

**Comment by mcarrano** [comment]
I see. I'm still thinking that it makes the most sense to present this as a variant of a dashboard (i.e. as part of the same demo) rather than a unique thing. But I agree that it makes the most sense to show a dashbar above something with a table view. Do you agree with that @doruskova or would you rather see Dashbar presented as a unique demo?

**Comment by doruskova** [comment]
@mcarrano Ok, I'll add it to a mockup with a dashboard and we can explain the usage in Dashboard guidelines.

**Comment by mcarrano** [comment]
Thanks for your efforts on the @doruskova . I am going to close this one as you've included the mocks as part of the dashboard issue here: https://github.com/patternfly/patternfly-design/issues/752
