### ISSUE TITLE
Enhance table component to support sorting in mobile view 

### ISSUE THREAD

**Issue by drcoolsanjeev** [patternfly/patternfly-design#919]
### Description
In current version of PF, there is no default feature to sort any column in mobile view. 

### Workaround 
To support this I have to create a seperate section in toolbar to allow user to select the column and the option for sorting.

### Suggestion
It would really be nice if PF provide sortable in mobile view as a default feature in next release. As it seems table are used widely in all projects.

**Comment by redallen** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
@drcoolsanjeev based on the design here, looks like the way to make this work would be to pass handling of sorting off to the toolbar when the table transforms to stacked columns (as you are suggesting). See https://www.patternfly.org/v4/components/table/design-guidelines#tables-on-mobile  Unfortunately we don't have a demo of this. I'm not sure what a better solution would be since in the mobile format, there are no longer clickable column headings.

**Comment by mcarrano** [comment]
This may also be a problem for other header actions like bulk selection.

**Comment by bgliwa01** [comment]
Here is a marvel of the proposed design: https://marvelapp.com/prototype/g894bfa

cc @mcarrano

**Comment by mcarrano** [comment]
This looks good to be @bgliwa01 . 

@mcoker @mattnolting can you also give this a look? The idea would be that when the table transforms into the stacked/mobile format, the Sort menu is also exposed within the toolbar. Do you see any problem with that approach realizing that the Toolbar and Table are separate components? Perhaps we would create a demo to show this.

**Comment by mcoker** [comment]
@mcarrano that sounds good to me, seems like it would be a manual implementation and a demo on our end would be great for showing how it can be done.
