### ISSUE TITLE
Tree-Table component - responsive behavior

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#931]
Want to introduce a tree-table component based on the Cloud Platform implementation.  You can see a live demo here: https://cloud.redhat.com/docs/api This works well for desktop, but need to consider what layout and interaction should be for mobile.

**Comment by mmenestr** [comment]
I don't have much background on this issue, but I just want to mention that the example that's linked to in this issue isn't really a normal tree-view because the content inside the expansion is "on-par" with the content in the rest of the rows in the table. 

In other words, I usually think of the items inside a tree view folder as subsets of its parents, unrelated to the rest of the folders/or items in the "table", but in this case, they ARE related and on-par with the rest of the rows outside of the immediate folder.

To contextualize this, the table rows show the APIs for each app in c.rh.c. But since all other apps only have 1 API, and Drift has 3, they decided to add the expansion to Drift to group the APIs up. So in the implementation linked, the rows inside the drift folder are technically "the same" as the rows outside of the folder, which to me make this a non-tree view.

If that's the use case you're actually trying to design for, then my 2 cents is that I would expect that the rows inside the expanded content would not be indented the way they are, and that they would appear in line with the rest of the rows.

Hopefully that makes sense?

**Comment by mmenestr** [comment]
I left a comment and then deleted it after studying the example a little bit more - so please ignore haha

**Comment by bgliwa01** [comment]
Here is a link to a Marvel for this design https://marvelapp.com/prototype/60jcb75 
cc @mcarrano

**Comment by mcarrano** [comment]
Thanks for posting this @bgliwa01 .

@mceledonia @mattnolting @nicolethoen @mcoker this proposal addresses the potential responsive behavior for the Tree Table. You'll see that we are looking at using a drill-down pattern to access nested levels of the tree, which is a common mobile pattern. Do you think this will work?

From a design spandpoint, I'm just wondering if we would make the ">" button to drill down larger/more prominent. What do you think @mceledonia ?

**Comment by mcarrano** [comment]
I have opened https://github.com/patternfly/patternfly/issues/3900 for tracking core implementation.

**Comment by mcarrano** [comment]
See https://github.com/patternfly/patternfly/pull/3943 for current proof of concept. Will close the design issue.
