### ISSUE TITLE
Need a way to indicate to user that filters are applied when catalog filter panel is closed

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly-design#932]
On desktop default, the filter panel is open on the [catalog view](https://github.com/patternfly/patternfly-design/issues/848#event-3545675093), but at any time the user can click the 'Filter' icon in the toolbar to toggle it shut. If the user applies filters and then toggles it shut (or goes to a smaller screen-width, where it is closed by default, they would not have a way of knowing that they are looking at a filtered view.

I chatted this through with @katierik and we both thought that a possible solution could be to apply a similar treatment when there's applied filters to the 'Filter' icon as we do with the bell in the masthead when there's new notifications. Here's a quick idea of what I mean -- there is likely a better visualization for this though too :)

Appearance when there's 5 filters applied
![Screen Shot 2020-10-15 at 4 04 20 PM](https://user-images.githubusercontent.com/19824574/96180426-67c03b00-0f00-11eb-9050-eec6d5801cea.png)

Appearance when hovered over
![Screen Shot 2020-10-15 at 4 04 27 PM](https://user-images.githubusercontent.com/19824574/96180498-81618280-0f00-11eb-9e18-9583d681d098.png)

**Comment by mcarrano** [comment]
@maryshak1996 I have moved this to our design backlog for further consideration. After discussing with @mceledonia it's not clear that placing a show/hide control in the toolbar is the best approach. We were thinking about perhaps making the filter panel a collapsible/resizable panel like a drawer. Let's discuss.

**Comment by mceledonia** [comment]
@maryshak1996 @mcarrano What do you think about this approach? Having a "collapsed" state of the filter panel - this lets us place the badge/indicator there, and also retain awareness of the panel while it is closed but taking up minimal space. 

This is a bit of a quick hack job and maybe it could have an arrow icon at the bottom, but to visualize the idea:
![image](https://user-images.githubusercontent.com/30935938/106484581-c55f9f80-647d-11eb-8097-7b9e043e2abb.png)

**Comment by mcarrano** [comment]
I like this approach @mceledonia . What do you think @maryshak1996 ?

@mcoker can you also take a look at this? I'm wondering if this filter panel is really just an instance of the new Sidebar component you defined for Jump Links. I could see wanting to show/hide that for similar reasons. Maybe this is just a sidebar that can be show of hidden by clicking an icon. The icon and the contents of the panel can be anything. What do you think?

**Comment by mcoker** [comment]
@mcarrano I can see that, there is a lot of overlap between the sidebar and an inline drawer. I hadn't thought of the sidebar having a collapsed state, though I don't see why it couldn't. I thought it was more of a side by side layout when there is horizontal space for the layout, and a stacked layout when there isn't. For a slide out panel, I assumed the drawer would be more suitable. This could also easily be a drawer - similar to the resizable, except the "collapsed" state just moves most of the drawer off the screen, and leaves a little bit to interact with - similar to resizing a drawer panel as small as it will go.

**Comment by mcarrano** [comment]
@mcoker Yeah, I think you make a good point that perhaps this panel is just a Drawer that can be collapsed (and possibly resized?). In that case, I wonder if we would just replace the "x" button with a "<-" to collapse and a "->" to expand. Or we can just use the existing splitter bar to let the user size the drawer as wide or narrow as they want. Although at some point the content becomes unusable below a certain size. What do you think @mceledonia @maryshak1996 ?

**Comment by mceledonia** [comment]
@mcarrano Here's our latest design proposal, aligning with the behavior of the toolbar as it is a similar interaction pattern. I have two versions below - 1. The indicator appearing on its own line, extending the vertical height of the page header area. / 2. Appearing in-line with the rest of the page header toolbar actions when the space is available.

I would like to get more thoughts on these tomorrow as I think the version on it's own line is the most clear as a toggle since it appears on the left-hand side of the section, but it does use an entire line of vertical height. The second version does not waste the space but makes the toolbar feel more busy and is disconnected from the proximity of the panel it is associated with. 

I just decided to add a third version where we right-align the indicator, placing it next to the full item count. While this sacrifices the proximity association, it is at least closer to another relevant item (total count) and doesn't take up the additional vertical height. 

1.
![image](https://user-images.githubusercontent.com/30935938/112186537-9c36d200-8bd7-11eb-8c24-d0d3a47fdb39.png)

2.
![image](https://user-images.githubusercontent.com/30935938/112186565-a658d080-8bd7-11eb-8945-1d0a72e544f9.png)

3.
![image](https://user-images.githubusercontent.com/30935938/112186600-afe23880-8bd7-11eb-8215-d3c0ca7a7208.png)

Option 3 would be my pick due to the reasons mentioned above

**Comment by mcarrano** [comment]
@mceledonia based on feedback from today's PF design share meeting, let's consider the following updates:

* perhaps separate the reporting of filters applied and showing/hiding the filter panel as separate concerns.
* consider a more general approach to showing and hiding the filter panel that could be generally applied to any drawer.

**Comment by mceledonia** [comment]
Here's a quick prototype I made to convey the idea. This solution would require us creating and shipping a custom icon, but that is something we can absolutely do thanks to the work of Brian and Coker! https://xd.adobe.com/view/dafffb62-bfa8-4fc4-ad35-001b409e70b1-8fac/

**Comment by mcarrano** [comment]
Thanks @mceledonia . Do you recall what's needed to create the custom icon? Is it just an SVG of each? If you can provide those I will open  a separate issue to add these.

cc @bdellasc

**Comment by mceledonia** [comment]
Here are the new icons for panel-open and panel-close, attached as SVGs. @mcarrano 
[panel-open-close.zip](https://github.com/patternfly/patternfly-design/files/6415720/panel-open-close.zip)
<img width="244" alt="image" src="https://user-images.githubusercontent.com/30935938/116894591-3ee36700-ac00-11eb-93de-7e09dfa1fa2c.png">

**Comment by bdellasc** [comment]
Did you add those icons to the Sketch exporter source file @mceledonia?

**Comment by mcarrano** [comment]
Thanks @mceledonia . I opened https://github.com/patternfly/patternfly/issues/4037 to add these to the core icon set. @bdellasc what do we need to do to add these to the website?
