### ISSUE TITLE
Enhance static drawer component to enable background color change

### ISSUE THREAD

**Issue by amysueg** [patternfly/patternfly-design#935]
- The designs for provisioning a Managed Kafka instance include a wizard that requires some supporting information to let the user know more about the cost of certain selections.
- The design proposes a right-hand pane in the wizard for this information.
- The current **static drawer component** presentation includes only a vertical separator between the page content area and the right-hand drawer.
- We would like a variant that supports changing the static drawer background color.
- Slides 14 - 24 show examples of the expected usage and look: https://docs.google.com/presentation/d/1OsvwZApq9LqfLHK9SJzJDjy7H7xBoM1El345PmwAz_g/edit#slide=id.ga0411b56df_0_331 

@jgiardino @lboehling @mcarrano

**Comment by mcarrano** [comment]
@amysueg we will get this on our roadmap. Do you need this in a particular time period?

**Comment by jgiardino** [comment]
@mcarrano The best timeline I have at the moment is by summit. Does that help?

**Comment by mcarrano** [comment]
Yes, that should  e doable @jgiardino . So I assume by March 2021 would work then?

**Comment by doruskova** [comment]
@mcarrano I took a look at this issue and I found a conflict with `#f0f0f0` (var black 200) that was used in this case. The same color is used in grey filled labels, badges and you can't put these components on a grey drawer that is using the same bg color. I was trying to find a different shade of grey and it looks that black 100 `#fafafa` would be fine. It's really close to white, but you can put everything if your use case needs it.
@jgiardino Do you want to put only text to this drawer on the right side? 

version 1: I like this version because the label doesn't blend with a background. 
![wizard-grey-v1](https://user-images.githubusercontent.com/32618096/105379356-08637c80-5c0d-11eb-97bd-4476e86fbccc.png)

version 2: the grey label starts to blend with a background. 
![wizard-grey-v2](https://user-images.githubusercontent.com/32618096/105379543-3779ee00-5c0d-11eb-9d13-592692d5fb0d.png)

**Comment by mcarrano** [comment]
Just as an aside, labels on a gray background are a known issue and we currently have an open issue to update the label designs to accommodate this (https://github.com/patternfly/patternfly-design/issues/967). 

@doruskova could we also see what this looks like when we add a splitter? Part of my concern was whether we need to also have an alternate color for the splitter (should someone choose to add one) or if the white splitter will be OK.

**Comment by jgiardino** [comment]
> @jgiardino Do you want to put only text to this drawer on the right side?

Our current plan is to only provide additional information. Having the option to include links and inline alerts and/or status icons could be something we will need as these requirements are further defined.

**Comment by doruskova** [comment]
@mcarrano Thank you! The new labels solved this problem :) However, 
- I like the white splitter more because visually it looks smooth and it's not too heavy on a screen. It says: "Hey, I'm here and you can use me if you need". 
- The grey splitter looks more that it belongs to the content on the right. I don't like that the grey splitter looks too heavy. It doesn't need such attention IMHO. 

I'd keep it white even if the drawer is grey `#f0f0f0`. WDYT? 

![wizard-grey-v1-white splitter](https://user-images.githubusercontent.com/32618096/105481873-ebc85280-5ca7-11eb-8f41-191460001268.png)
![wizard-grey-v1_splitter](https://user-images.githubusercontent.com/32618096/105481883-ee2aac80-5ca7-11eb-9a67-4cbb957d137f.png)


I'm also adding the version without a splitter, but with var black 200 (`#f0f0f0`)
![wizard-grey-v3](https://user-images.githubusercontent.com/32618096/105488641-3a7aea00-5cb2-11eb-9b84-f7021a261cb8.png)

**Comment by mcarrano** [comment]
This looks great @doruskova I agree with you about the splitter. @mceledonia @mcoker can you also take a look? If there are no further objections, I will go ahead and open a core issue.

**Comment by mcoker** [comment]
@mcarrano lgtm

**Comment by mcarrano** [comment]
Thanks @doruskova . I will move this along to be implemented. Core issue: https://app.zenhub.com/workspace/o/patternfly/patternfly/issues/3813
