### ISSUE TITLE
Button for dark theme

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design#941]
Evaluate current button variants against a dark background and recommend any needed customizations to work for dark theme. Concerned that just flipping black to white breaks existing visual hierarchy.

**Comment by doruskova** [comment]
@mcarrano Update on hover states (lighter background) for buttons[ here](https://marvelapp.com/prototype/963bhhh/section/1224558)

**Comment by doruskova** [comment]
@mcarrano Updated [design](https://marvelapp.com/prototype/963bhhh/screen/75558357) for secondary and tertiary buttons.
I noticed some issues in a primary button: 
- The new blue color `#1FA7F8` doesn't have enough contrast with a white text in a button. The previous one works. 
- If I use the new blue color > need to change the text to black, but the hover state uses `#0066cc`color which is a darker blue and it doesn't work (contrast issue) with black text. 

@mceledonia WDYT? Can we make an exception for buttons and use the previous blue you found? 

The most usual approach for secondary and tertiary buttons is: 
- keep the border for a secondary button
- remove the border for a tertiary button and keep the hover state white so that it's clear that it's not just a link.

**Comment by doruskova** [comment]
@mcarrano Updated design for buttons [here](https://marvelapp.com/prototype/963bhhh/screen/75558357)

**Comment by mcarrano** [comment]
Thanks @doruskova . I will close this then.
