### ISSUE TITLE
Wizard -Required Steps Indication Guidance

### ISSUE THREAD

**Issue by nding-anges** [patternfly/patternfly-design#965]
We're hoping to get some more guidance/clarification on the indication of the required steps within the wizard.
When creating a connector in Debezium, only the first two steps in the wizard are required for users to complete a configuration and the last three steps are optional. So there is a requirement to indicate the required steps on the wizard.
The current design is using the asterisk (*) as a required mark on the first two steps displays. See a screenshot below.
We'd like to make sure that the current design is consistent with PatternFly and get more guidance at this point. 
<img width="891" alt="屏幕快照 2020-12-08 下午1 55 20" src="https://user-images.githubusercontent.com/34368385/101445791-1743e780-395d-11eb-8e7f-0c6d12a8c87c.png">

**Comment by mcarrano** [comment]
@nding-anges We currently do not have a way to indicate required steps in a wizard as you are showing in this design. While it is not documented anywhere, the approach that I've see others take is rather that marking steps as required, you can include a button to skip the optional steps that appears after the user completes the first two steps. I had earlier discussed this approach with @lboehling . Marking steps as required would actually have no effect since in this design the user would still need to skip through all steps correct? We should probably add this to the design guidelines here: https://www.patternfly.org/v4/components/wizard/design-guidelines

**Comment by amysueg** [comment]
I think that the recommendation to add the Finish button after the user completes the required steps is the right way to go, and I agree with @mcarrano  that we should add that to the documentation/guidelines for Wizards. Thanks for bringing this up, @nding-anges

**Comment by mcarrano** [comment]
Thanks @amysueg . I have opened https://github.com/patternfly/patternfly-org/issues/2335 to track requested documentation updates and will close this out.

**Comment by nding-anges** [comment]
Thanks @mcarrano
