### ISSUE TITLE
Improve distinction of interactive vs. non-interactive lables

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design#971]
Today, it's difficult to distinguish if a label is clickable or not. In OpenShift, we are trying to come up with some conventions to make that distinction more clear. We originally were thinking of only using outlined labels for non-interactive cases and filled labels for interactive cases... but even the outline/fill styles don't seem like they're enough to make it clear that the label is interactive.

I brainstormed with @megan-hall and we thought adding some sort of kebab or actionable button may help...

This is what chrome does for available updates:
<img width="88" alt="Screen Shot 2020-12-15 at 12 00 01 PM" src="https://user-images.githubusercontent.com/30870144/102248277-005a4380-3ecf-11eb-97de-a1d9c8faa072.png">

cc: @bmignano

**Comment by bmignano** [comment]
Agree that we need a way to distinguish clickable and non-clickable labels! We use labels fairly frequently throughout the OpenShift console and there's no way to know if you can interact with them unless you hover over each one individually.

A couple thoughts to consider on the suggestion above:
* The Update label on Chrome opens a menu, so I think the kebab makes sense there. But if we use that, what about instances where a user could click a label to open a side panel? Or to redirect them to another page or show a popover? I think since clicking a label in OS could result in a number of different scenarios, I'm not sure the icon scales well across cases. Maybe we could explore other potential icons to indicate more vague interactivity?
* Another consideration is that we often use an icon at the front of the label as well. Would the label look too overwhelming with an icon on both sides of the label text?

I'd have to think more on some more concrete suggestions, but I'm excited for us to add this enhancement!

**Comment by mcarrano** [comment]
I think this is something we can consider, however I agree with @bmignano that the kebob is not the best choice here. @maryshak1996 can you take a look at this and let us know if you have any ideas? Since you are re-thinking visual design of the labels, I think it would be good to throw this request into the mix.

cc @mceledonia

**Comment by maryshak1996** [comment]
Designs for this topic as well as #967 can be seen here: https://marvelapp.com/prototype/553965i
Basically, we are not going to dictate to a designer how to differentiate (or if they need to differentiate) between clickable and not clickable labels. Instead, we will include a section in the labels guidelines around strategies for differentiating the two if it’s needed in a product.

- If you have a context that has a mix of read-only and clickable labels, consider using heavy labels for read-only and light labels for clickable, or vice  versa. Whatever your convention is, be consistent without it throughout your UI. You can see examples of suggestions in the labels demo.
- Only linked labels should have hover and focus states. Note: if using a ‘clear’ icon on a label, this has a separate click target, hover and focus state.

**Comment by mcarrano** [comment]
Thanks for including these notes @maryshak1996 .

So I think we would move this issue over to documentation then. @bmignano @mmenestr do you know if we already have an open issue for labels guidelines or should I transfer this over to the -org repo for further tracking?

**Comment by bmignano** [comment]
Sounds good! @mcarrano I believe Margot made this issue to cover these additional guidelines: https://github.com/patternfly/patternfly-org/issues/2329

**Comment by mcarrano** [comment]
OK. In that case I am going to close this issue in favor of that open documentation story.
